### ISSUE TITLE
Can we add diagnostics to no_warnings()?

### ISSUE THREAD

**Issue by dboehmer** [Test-More/test-more#1004]
In my code I have some lines like

```perl
ok no_warnings { ... }, "code works without warnings";
```

This is fine as long as the test suite passes. But each time I develop and find this test statement to fail I need to change the code to actually see the warnings. Can we improve that?

Basic test case: process ID `$$` from warning invisible in test output

```console
$ perl -MTest2::V0 -e 'ok no_warnings {warn $$}; done_testing'
# Seeded srand with seed '20240914' from local date.
not ok 1
# Failed test at -e line 1.
1..1
```

Could `no_warnings` print the warnings automatically with `diag()`?

Workaround is to simply use `is warnings { ... } => []` but then `no_warnings` was a rather useless function :pensive:

**Comment by exodist** [comment]
I agree that something is needed here. I have an idea, I will play around with it and make something work.

**Comment by exodist** [comment]
Can you give this branch a try and see if it meets your needs?
https://github.com/Test-More/test-more/pull/1005

Assuming it does, I will need to run downstream testing, and if anything breaks I will have to release this functionality as a new Test2::V1 bundle

**Comment by dboehmer** [comment]
I made my script issue three warnings for the 2nd run and with your PR branch the test output is now much more useful:

```TAP
ok 2 - no warnings with empty database
not ok 3 - no warnings with test data

# Failed test 'no warnings with test data'
# at t/script_dbck.t line 23.
# a at .../coocook/lib/Coocook/Script/Dbck.pm line 42.
# b at .../coocook/lib/Coocook/Script/Dbck.pm line 42.
# c at .../coocook/lib/Coocook/Script/Dbck.pm line 42.
```

My test suite still passes fine (without the mentioned modification).

I am astonished that Test2::V0 had been around since 2017 and now you’re going to add Test2::V1 just for my niche feature request?! :astonished: The overall usefulness of this change and the technical implementation details are a bit over my head. That’s why I have no comment on the PR itself.

**Comment by exodist** [comment]
I only need a V1 if this change breaks any downstream modules. It changes the output of 2 test functions, so any downstream modules that add test tools that use these under the hood could have their tests broken. It is unlikely though, so I suspect we will stick with v0

**Comment by exodist** [comment]
I should also add that this issue hit me yesterday with `lives` so it is not just you hit by this :-)
