### ISSUE TITLE
frescobaldi does not build due to qt5-qt5location problem that seems due to an on-going boost problem

### ISSUE THREAD

**Issue by JJHelly** [Test-More/test-more#1008]
Aloha.

I changed to Sequoia 15.0 and had to re-install macports but frescobaldi won't build due, apparently, to qt5-qt5location failure.  When I dug into this a bit, I changed the permissions on the src directory and ran make manually and see this boost error.  It seems that similar errors have been reported previously but this is about as far as I can go without additional help.

J.

In file included from deps/boost/1.65.1/include/boost/mpl/integral_c.hpp:32:
deps/boost/1.65.1/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'int_float_mixture_enum' [-Wenum-constexpr-conversion]
deps/boost/1.65.1/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |

**Comment by exodist** [comment]
Did you send this issue to the wrong project? I am not sure what this has to do with Test::More?
