### ISSUE TITLE
Take part in Hacktoberfest

### ISSUE THREAD

**Issue by mikkoi** [Test-More/test-more#1009]
Let's open the repository for Hacktoberfest 2024 participants:
[Hacktoberfest Participants: Maintainers](https://hacktoberfest.com/participation/#maintainers)

* Add the “hacktoberfest” topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.
* Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.

**Comment by exodist** [comment]
Sorry, was not able to devote the time needed to even look at this back in October. Maybe next year.
