### ISSUE TITLE
Confusion as to $Test::Builder::IO::Scalar::VERSION

### ISSUE THREAD

**Issue by jkeenan** [Test-More/test-more#1016]
Today I saw that a new version of Test-Simple (1.302205) had been released and I decided to see whether it was testing well enough to be synched into the Perl 5 core distribution in advance of a monthly development release scheduled for Dec 20 2024.

I do not believe this version should be synched into blead.  When I attempted to install the new tarball into recent (Dec 2024) perl installations on my machines, I repeatedly got a message like this:
```
allow_installing_module_downgrades: EXODIST/Test-Simple-1.302205.tar.gz 
(called for Test::Simple) contains downgrading module(s) 
(e.g. 'Test/Builder/IO/Scalar.pm' would downgrade installed '2.114' to '1.302205'). 
Do you want to allow installing it? [no]
```
Indeed, in a perl I locally installed on December 4, I got this:
```
$ ack '\$VERSION' blead/lib/perl5/5.41.7/Test/Builder/IO/Scalar.pm
use vars qw($VERSION @ISA);
$VERSION = "2.114";
```
But in the tarball for 1.302205 I just downloaded, I got this:
```
$ ack '\$VERSION' lib/Test/Builder/IO/Scalar.pm 
our $VERSION = '1.302205';
```
Can you investigate?  Thank you very much.

**Comment by haarg** [comment]
This module is used for compatibility with perl 5.6, where it isn't possible to open a file handle to a scalar reference.

However, this dist no longer supports perl 5.6. There may be other things preventing it from working, but the first problem is that it requires Term::Table, which requires perl 5.8.1.

I would recommend just removing the Test::Builder::IO::Scalar module and cleaning up the places that try to load it.

**Comment by exodist** [comment]
@haarg that is probably the best option.

**Comment by exodist** [comment]
I am running downstream tests before uploading this to pause... Assuming they all pass and nothing downstream is broken from this being missing, I will upload it.
