### ISSUE TITLE
Make the purpose of done_testing and the plan clearer

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#151]
A few people were doing this:

    use Test::More;  END { done_testing }

This defeats the protections of `done_testing` because...

    1. done_testing() should only run if all your tests have executed.
    2. END blocks always run, even if your code exits or dies.

I figure people should be able to work that out from those principles, but @dagolden pointed out that #1 isn't documented.  The whole point of the plan is a bit muddled.

So....

    1. Improve the docs for done_testing() to include more information to help a user know how to use it correctly.
    2. Avoid simply listing things not to do, like END { done_testing }

I only caught three people doing `END { done_testing }`, not enough to take up space in the docs.  I'd rather focus on conveying the principles so people can think intelligently about `done_testing` rather than list every mistake we've seen.

**Comment by exodist** [comment]
I am just going to document the issue. Adding END detection is a problem because using caller to detect END is the only viable way, but that causes SEGV in some cases, which is bad.
