### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#173]
Test coverage is very good, but we can always use more tests.

Use Devel::Cover to run a coverage analysis (`cover -test`) and use the results to suggest where more testing is needed.

Note: Devel::Cover currently has a bug where it throws a lot of warnings about accessors when dealing with Moose or Mouse.  They're safe to ignore.  See https://rt.cpan.org/Ticket/Display.html?id=71680

Running under coverage may cause tests to fail.  Ignore it, it's not your problem.

**Comment by exodist** [comment]
This appears to have been mainly aimed at the Test::Builder2 project. I am closing, Test coverage with the Test2 stuff is quite good. I will of course always accept patches that improves that.
