### ISSUE TITLE
Update Test::Tutorial

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#175]
Test::Tutorial is rather out of date, written at a time when testing was not an accepted practice.  The audience, tools and examples have changed.

Go through Test::Tutorial and bring it up to date.  Here's some suggestions.

* Change the focus away from people who don't want to test towards people who do want to test (the convincing stuff can be put into its own section).
* Update the example to use a more recent module OR ship a copy of the broken Date-iCal as an example people can work on.
* Focus on done_testing() rather than plans.
* Mention common 3rd party modules like those used by Test::Most.
* Make use of the `note "..."; { ...tests here... }` style of test blocks.

Adding more is also useful.

**Comment by exodist** [comment]
This will be solved by Test2::Manual, which is in progress.

**Comment by exodist** [comment]
This ticket no longer serves a purpose, closing.
