### ISSUE TITLE
Die in the ending if there's anything on the TODO stack

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#32]
* GC-ID:     [10](http://code.google.com/p/test-more/issues/detail?id=10)
* GC-Labels: Type-Defect, Priority-Medium, Component-Test-Builder
* GC-Status: Assigned
* GC-Attachments: No

-----

* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2008-08-22T20:55:34

To guard against an un-ended todo_start() from silently making everything
TODO, die if there's anything left on the Todo_Stack at the end of the test.

-----
* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2008-08-22T20:56:40

The message should display the messages on the stack and, if possible, where they
were declared.

-----
* From: [curtis.poe at Google Code](http://code.google.com/u/curtis.poe/)
* Date: 2008-08-22T23:15:08

Basically, I'm going to have add package knowledge to this.  However, if there is
more than one todo_start in a single package, would their still be a problem? 
Backing out of one TODO would still leave another TODO and things would still work,
but the TODO message would be wrong.  I'll have to think about this.

-----
* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2008-08-22T23:40:00

I don't follow what packages have to do with this.  There's only a single TODO stack.
 Here's a sketch.

if( @{$self->{Todo_Stack}} ) {
    diag "The following was left on the TODO stack:";
    diag "  $_" for @{$self->{Todo_Stack}};
    die;
}

If $self->todo_start tracks caller line and file information in the stack then it can
be reported as part of the error.

-----
* From: [curtis.poe at Google Code](http://code.google.com/u/curtis.poe/)
* Date: 2008-08-23T08:27:29

Yes, using file and line works better than packages for this.  And since it may not
have been clear, I was referring to tracking packages to ensure that a todo_end
didn't try to end a todo in another package.  While some might find this an annoying
limitation, it might prevent nasty bugs where we wind up with that dangling todo_end.

So, you initially referred to 'end of the test'?  Are you saying a DESTROY block? 
I'm already proving Test::Builder::DESTROY in Test::Most because I need that for
failure callbacks in the case of the last test failing.

If you want a DESTROY block to do "end of test" work, can we make a publicly
sanctioned hook that DESTROY will call?

Cheers,
Ovid

-----

**Comment by exodist** [comment]
This would be a breaking change. I am closing this ticket as the value to risk ratio is not worth it.
