### ISSUE TITLE
Better is_deeply diagnostics

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#35]
* GC-ID:     [2](http://code.google.com/p/test-more/issues/detail?id=2)
* GC-Labels: Type-Enhancement, Priority-Low
* GC-Status: Assigned
* GC-Attachments: No

-----

* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2008-08-08T00:37:10

See
http://groups.google.com/group/test-more-users/browse_thread/thread/63d952b022756d1a

-----

**Comment by exodist** [comment]
Cannot change is_deeply's diagnostics without breaking a lot of downstream things. However the deep comparison diagnostics in Test2::Suite are much improved. Closing this in favor of the Test2 solution.
