### ISSUE TITLE
Option and environment variable to bail out at the end of a failing test.

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#373]
"Bail on fail" is often requested, but cannot be implemented reliably for reasons discussed in [Stop On Fail](http://github.com/schwern/test-more/wiki/Stop-On-Fail).

What we can implement is an automatic bail out at the end of the test file if the test fails.  This will at least keep the whole test suite from running, useful for things like `t/00compile.t`.

A generic on fail handler would look like this:

    use Test::More on_fail => sub { BAIL_OUT("Because") };

This subroutine would run as the test file is ending.

There would also be an environment variable `TEST_BUILDER_ON_FAIL` to do the same.  `TEST_BUILDER_BAIL_ON_FAIL` would be a convenience method for `sub { BAIL_OUT("Because") }`.

CC @Ovid @rocky @pdl @karenetheridge

See #319 for extended discussion.

**Comment by exodist** [comment]
The new Test2 infrastructure makes this simple. In fact Test2::Suite has Plugin::DieOnFail and Plugin::BailOnFail that does the right thing. closing this ticket,
