### ISSUE TITLE
Easy way to turn on utf8 encoding

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#374]
Provide an easy way to turn on UTF8 filehandle encoding both as a Test::Builder method and an import option.

    # Would add ":encoding(utf8)" to output, todo_output and failure_output.
    use Test::More utf8 => 1;

    Test::Builder->new->add_io_layers(@layers);

This makes life easier for people using UTF8 rather than having to mess with `use open` and do it at the right time.

**Comment by exodist** [comment]
The Test2 stuff makes it very easy to do this as a Test2::Plugin::TermEncoding or similar. No need to make this part of Test-Simple.
