### ISSUE TITLE
Status of Test::Tester::CaptureRunner unknown

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#531]
I just discovered that the Test::Tester::CaptureRunner is in 1.001014 and not in _096.

A word should probably be said about the demise. I have no interest in it at all, but it just turned out that my testing in the last weeks was not as intense as I had thought because of this single file. This package caused a package downgrade and I did not notice it until now.

I'm now fixing my test setup.

**Comment by exodist** [comment]
Ah, I can add a stub package. It is no longer needed or used, but I guess a stub is in order.

**Comment by exodist** [comment]
https://github.com/Test-More/test-more/commit/a8ac845e499e7fad45d09ace8a568b920214bffa
