### ISSUE TITLE
[PATCH x 3] Test-Simple: reduce compiler warnings and stderr noise

### ISSUE THREAD

**Issue by iabyn** [Test-More/test-more#535]
Dear maintainer of a dual-lived CPAN distribution: I'm currently attempting
to get bleadperl to be warnings-clean; i.e. where
    (./Configure && make) 2>errs
leaves no lines in 'errs'. Recently bleadperl made the -W options passed
to the C compiler more fascist, and in addition we're trying to get blead
to compile and run cleanly under clang's -fsanitize=undefined option.  Due
to that and other reasons, bleadperl's build is currently very noisy.

I've created three patches on the davem/cpan-warn branch in the perl
repository,
http://perl5.git.perl.org/perl.git/shortlog/refs/heads/davem/cpan-warn,

    fc393fb Test::Simple: less test noise on STDERR
    0a38aa3 Test::Simple: silence some STDERR noise
    4d7f886 Test::Simple: avoid warnings in subtest tests

that reduce the noise of your distribution when built as part of
bleadperl.

It would be great if they could make it into a new release of your
distribution in time for incorporation into perl-5.22.0. Our
timetable is:

  2015-01-20  5.21.8          Contentious changes freeze
  2015-02-20  5.21.9          User-visible changes freeze
  2015-03-20  5.21.10         Full code freeze
  2015-05-20  5.22.0          Stable release!

so for example if a new release of your distribution included contentious
features, then it would need to be merged into blead *prior* to the 20th
of Jan.

Thanks,

Dave M.

**Comment by jkeenan** [comment]
On 01/12/2015 11:00 AM, iabyn wrote:
> Dear maintainer of a dual-lived CPAN distribution:

I'm not sure which dual-lived CPAN distribution I'm supposed to be a 
maintainer of.  Can you clarify?

I'm currently attempting
> to get bleadperl to be warnings-clean; i.e. where
>      (./Configure && make) 2>errs
> leaves no lines in 'errs'. Recently bleadperl made the -W options passed
> to the C compiler more fascist,

Please, no rhetorical overkill.

and in addition we're trying to get blead
> to compile and run cleanly under clang's -fsanitize=undefined option.  Due
> to that and other reasons, bleadperl's build is currently very noisy.
>


Thank you very much.
Jim Keenan

**Comment by karenetheridge** [comment]
This entire conversation is in the Test-More issue queue, so the patches
are for that dist :)  People-not-Exodist can safely ignore this ticket.

**Comment by iabyn** [comment]
On Mon, Jan 12, 2015 at 03:45:09PM -0800, James E Keenan wrote:
> On 01/12/2015 11:00 AM, iabyn wrote:
> > Dear maintainer of a dual-lived CPAN distribution:
> 
> I'm not sure which dual-lived CPAN distribution I'm supposed to be a 
> maintainer of.  Can you clarify?

The clue's in the subject :-)

Subject: Re: [test-more] [PATCH x 3] Test-Simple: reduce compiler warnings

-- 
print+qq&$}$"$/$s$,$a$d$g$s$@$.$q$,$:$.$q$^$,$@$a$~$;$.$q$m&if+map{m,^\d{0\,},,${$::{$'}}=chr($"+=$&||1)}q&10m22,42}6:17a2~2.3@3;^2dg3q/s"&=~m*\d\*.*g
