### ISSUE TITLE
note() partial message then continue

### ISSUE THREAD

**Issue by epa** [Test-More/test-more#536]
note() writes a complete line of text to the console.  That is usually what you want.  But sometimes when converting an existing program into a test case you have code which calls print() several times, only putting a newline on the last one.  It would be useful to have note_print() which outputs part of a note, only ending it on a newline character.  The # character is added at the start of each line.  That would be a drop-in replacement for print().

This would also be useful for progress indicators which are more readable on a single line:

    note_print 'doing something slow to look for spranks... ';
    my @spranks = slow_operation();
    note_print scalar(@spranks) . " found.\n";

**Comment by exodist** [comment]
With the new internals a note is an object that is constructed and passed to the Test::Stream object where it is eventually output. So to do what you want would actually be to construct a Note object piecemeal, then send it once it is complete.

It might make sense to make it easier to create events without sending them, which would allow for something like this:

```
my $note = $context->build_note;
$note->append(@stuff, "the end");
$context->send($note);
```

Which would allow you to do what you want.. but it would be just as easy to do this:

```
my @parts = (@stuff, "The end");
... Stuff that adds test to @parts ...
$context->note(join " ", @parts);
```

**Comment by epa** [comment]
Maybe then a note whose last character is backslash should be printed without the traiiling newline (or backslash), so the following note can continue on the same line. Ugly but would allow progress indicators etc. The newline would be printed before any non-note output that follows.

**Comment by exodist** [comment]
There are a couple issues with this still:

* What if the test is threaded, or forks? Output would be scrambled.
* What if there are actual prints in other places?

Other things that have an effect:

Test::Builder clones the standard filehandles, and modifies them. printing to STDERR and firing off a note do not use the same filehandle (on perls side).

Also what about anyone downstream who happens to end a note with a backslash? I don't expect this to actually be an issue, but we must consider it.

I also do not like the idea of using a backslash for this.

Lets take a step back. Perhaps what you want is not a change to how note works, but a new custom event type? With the Test::Stream internals you can create your own type of event. Test::Stream::Event::Buffered perhaps. Simply creating that subclass of Event, and copying what Test::Stream::Event::Note does will give you 90% of what you need. You could then override to_tap to do as you need.

The likely problem here is that to_tap is expected to not have a newline, and one is added for you. For your purpose though you can have to_tap return an empty string, and handle printing yourself.

**Comment by haarg** [comment]
Is this purely for ease of porting, or do you see some general value in doing this?

**Comment by epa** [comment]
It's not a big deal - I wanted to make progress output look pretty by appearing gradually as a single line of text.  Clearly the way things work is a bit more complex than I thought (that's usually the way, right?).  In the end it doesn't matter if the output appears over ten lines instead of one.  So I think this report can be closed.  Thanks for your responses.
