### ISSUE TITLE
META: add conflicts prereq for old Test::SharedFork

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#539]
Old versions of Test::SharedFork are incompatibles with the new Test::Builder (I had "missing TB2::History" errors).

It would be helpful to add a [conflicts prereq](https://metacpan.org/pod/CPAN::Meta::Spec#Prereq-Spec) dependency in META v2.

**Comment by dolmen** [comment]
Note that it would be also useful to list all modules that had to be fixed (like Test::SharedFork) in future blog posts.

**Comment by karenetheridge** [comment]
The latest release has no Changes entry, so it's hard to see if this is the fixed version or if it was a previous one -- https://metacpan.org/changes/distribution/Test-SharedFork

**Comment by exodist** [comment]
I released 0.29, it is the version that fixes support for the new stuff. I would do a new release with a better changes file, but I could not figure out the dist build system and how to do it right at a glance, and have no time to learn it. Hopefully tokurom or someone who understands it can do a proper release.

**Comment by dolmen** [comment]
Thanks @exodist !
And @dolmen-- for not had a look to META before submitting.

**Comment by dolmen** [comment]
@karenetheridge Yep, tokuhirom/Test-SharedFork#21.
