### ISSUE TITLE
Objects passed to note kept alive until global destruction

### ISSUE THREAD

**Issue by haarg** [Test-More/test-more#540]
In Test::More 1.301x, if you pass an object to note (and likely other things), the object will be stored and kept alive until global destruction.  This prevents a DESTROY sub from being called at the intended time.  I would have expected the object to be stringified and only the string representation stored.

**Comment by dolmen** [comment]
Here is a test case:

```perl
use strict;
use warnings;
use Test::More tests => 1;
use B;

my $x = \(my $y);

# In newer TB, the reference to note's argument is kept and breaks the following test
note $x;
is(B::svref_2object($x)->REFCNT, 2, "refcnt=2");

done_testing;
```
