### ISSUE TITLE
Test::Builder::plan monkey patch alters behavior of done_testing

### ISSUE THREAD

**Issue by haarg** [Test-More/test-more#541]
In old Test::Builder, overriding Test::Builder::plan would not impact the behavior of done_testing.  Code to demonstrate the difference:
```perl
use strict;
use warnings;
use Test::More;

ok 1;

no warnings 'redefine';
*Test::Builder::plan = sub {};

done_testing;
```

**Comment by exodist** [comment]
Are you aware of anything impacted by this? Would be helpful to see a situation that breaks from this, though that is obviously not required to fix it.

**Comment by haarg** [comment]
https://metacpan.org/source/HAARG/strictures-1.005005/xt/pod.t

Some Test:: modules have functions that do their own plan.  To use more than one of those functions within a single test script, one workaround was to monkey patch plan to be a noop, then use done_testing at the end.

The change in behavior broke that test, which I've since updated to avoid needing the monkey patch.
