### ISSUE TITLE
boolean.pm fails tests with Test-Simple-1.301001_097

### ISSUE THREAD

**Issue by dagolden** [Test-More/test-more#546]
But with Test-Simple-1.001014 it passes.

Output from cpanm log with 1.301001_097 below (on Perl 5.20.0 with threads):
```
Building and testing boolean-0.43
cp lib/boolean.pm blib/lib/boolean.pm
cp lib/boolean.pod blib/lib/boolean.pod
PERL_DL_NONLAZY=1 "/Users/david/.plenv/versions/20.0t/bin/perl5.20.0" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/000-compile-modules.t .. ok
t/boolean.t .............. ok
t/export.t ............... ok
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Bareword found where operator expected at (eval 20) line 1, near "9ist"
        (Missing operator before ist?)
t/json.t .................
Failed 3/3 subtests
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Use of uninitialized value0 in concatenation (.) or string at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/More/Tools.pm line 36.
Bareword found where operator expected at (eval 18) line 1, near "5ist"
        (Missing operator before ist?)
Use of uninitialized value0 in method with known name at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/Stream/ArrayBase.pm line 62.
Use of uninitialized value0 in method with known name at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/Stream/ArrayBase.pm line 62.
Can't locate object method "" via package "Test::Stream::Event::Diag" at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/Stream/ArrayBase.pm line 62.
# Looks like your test exited with 255 before it could output anything.
t/truth.t ................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 8/8 subtests

Test Summary Report
-------------------
t/json.t               (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
t/truth.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 8 tests but ran 0.
```

**Comment by rjbs** [comment]
Confirmed.  That "value0" is odd.  "method with known name" less so, but still a bit odd.

:-/

**Comment by haarg** [comment]
This doesn't really have much to do with Test::More.  A reduced case of the problem
```perl
use boolean -truth;

my $name = 'welp';

my $sub = sub {
  warn "what\n";
  my $str = $name;
};

$sub->();
```
This produces `Warning: something's wrong at test.pl line 6.`.  The string inside the sub is undef.  The extra code in Test::More causes the strings to have corrupted nonsense (the code it tries to eval sometimes looks like "5ist/truth.teq") rather than undef, but it's still the same root cause of boolean.pm breaking the interpreter.

**Comment by exodist** [comment]
So is there something I need to do to fix this on my end? If not then is there something I can do to make my code more robust so that the error messages are more sane? Or is this something where the new stuff revealed a previously hidden bug and no action is needed on my end? I am bot familiar with 'boolean.pm'.

**Comment by dagolden** [comment]
I'd like it to be more robust.  This line in particular concerns me.

```
Can't locate object method "" via package "Test::Stream::Event::Diag" at /Users/david/.plenv/versions/20.0t/lib/perl5/site_perl/5.20.0/Test/Stream/ArrayBase.pm line 62.
```

And I don't understand what's going on in Test::More::Tools.

I'm concerned that the release candidate seems to be doing something too clever that is tickling this bug in a way that stable Test::More is not.  The fact that it's hard to diagnose because everything is being washed through eval concerns me as well.

For instance, I don't see where any of the strings "value0" or "5ist" or "9ist" are coming from.  It's not coming from the test files:

* https://metacpan.org/source/INGY/boolean-0.43/t/truth.t
* https://metacpan.org/source/INGY/boolean-0.43/t/json.t

**Comment by exodist** [comment]
The eval in this case is not new, it has been there forever. It is a valuable eval as it makes it obvious where someone has made a mistake when they do. It may be overly clever, but it is not new clever, and removing it is not really an option for legacy reasons. Though even without legacy I would be in favor of keeping the feature it provides.

Now as for why This breaks and old doesn't that has to do with code reuse. Specifically when it comes to Test::More's guarantee to not change $@ and $!. Both versions do it, but there are small differences in how they do it. I think that the new way is in General better and more sustainable, but I wrote it so I am ready to listen to opposing opinions. (Old code would localise those vars on it's own all over, new code uses a sub that takes a block and localizes them for you, but it also has extra logic to work around a Windows bug where local + fork = crash, making the new stuff fix a long standing Windows bug)

Haarg just issued a pull request that works around the issue. I think the pull request is an improvement even without knowing about this bug, and I will merge is very soon.

**Comment by dagolden** [comment]
I've dug into haarg's example and "value0" is coming from the Perl interpreter itself.  boolean.pm -truth is breaking how string *literals* are treated when string assignment is also happening.  This is really a perlbug, and I've opened https://rt.perl.org/Ticket/Display.html?id=123698.  Test::More is just a victim.

if haarg's PR works around the issue, then I'm comfortable with it being applied to close this issue.

**Comment by haarg** [comment]
The difference between the old and new Test::More for this issue is mainly just a matter of code organization.  The old code was just lucky that it didn't have any string literals in closures.
