### ISSUE TITLE
Separate "manual" diag messages and the "Failed [...]" messages (Test::Builder)

### ISSUE THREAD

**Issue by biffen** [Test-More/test-more#554]
Using `Test::Builder`'s `ok()` I get a "*Failed test [...] at [...] line [...]*" for every failed test. I don't want those. Since they are internally printed using `diag()` (see code below) I can get rid of them by disabling  diagnostic messages (`no_diag()` (but that still prints an extra `\n`)), but I would still like to be able to use `diag()` myself for other things.

Would it be possible to have a separate setting for whether these "*Failed [...]*" messages get printed?

I (think I) found the code in `Test/Builder.pm:878`:

```perl
    unless($test) {
        my $msg = $self->in_todo ? "Failed (TODO)" : "Failed";
        $self->_print_to_fh( $self->_diag_fh, "\n" ) if $ENV{HARNESS_ACTIVE};
 
        my( undef, $file, $line ) = $self->caller;
        if( defined $name ) {
            $self->diag(qq[  $msg test '$name'\n]);
            $self->diag(qq[  at $file line $line.\n]);
        }
        else {
            $self->diag(qq[  $msg test at $file line $line.\n]);
        }
    }
```

If only that `unless` would also check `$self->something` to determine whether to print those messages.

**Comment by exodist** [comment]
I would be willing to accept a patch for something like this. I would call it no_error_diag(). Please write your patch against current master, which is much much different from the stable currently on cpan. The new guts will be going live fairly soon.

**Comment by exodist** [comment]
In the Test2 system it is not difficult to bypass the automatic diagnostics. I am closing this as patching Test::Builder for this is not wise from a stability standpoint.
