### ISSUE TITLE
Alternative Release Proposal

### ISSUE THREAD

**Issue by exodist** [Test-More/test-more#590]
# What Test::Stream and Test::Builder will look like

In this new proposal Test::Stream will be an independent testing base, with an independent ecosystem. When used on its own it will not try to implement any Test-Builder compatibility. Test::Builder and Test::Stream will both be written to throw an exception if they load while the other is loaded.

There will be a module, Test::Compat, or Test::Stream::Builder, that will load a very specific and limited backwards compatibility. This backcompat will support any tools that use the public Test::Builder API, with some exceptions we choose to omit. Any tool that wishes to work with both systems will be restricted to the Test::Builder published API. Loading the backcompat module will avoid the exception that would otherwise be thrown if both systems are loaded. Test::Stream, or Test::Compat will need to be loaded before any Test::Builder tools if you wish to mix them.

We will tell Test::* module authors that they should NOT simply switch their tools to use Test::Stream instead of Test::Builder as that could break anyone that uses their tool along with other Test::Builder tools. However they can choose to implement Test::TheirModule::Stream and Test::TheirModule::Builder where Test::TheirModule simply loads the current one depending on if Test::Stream is loaded.

Test::Stream::More will be a drop-in replacement for Test::More for anyone who wants to change an existing test to use the new system. Test::Compat will do some magic to make anything that loads Test::More after Test::Compat is loaded use Test::Stream::More.

Test::Stream::More is focused on being a drop-in replacement for Test::More, there should be a new Test::XXX module that is the actual 'key' module we want people to use instead of Test::More. I have yet to decide what to call this, but it will be where we can provide new tools, fixed versions of tools that are flawed in Test::More, but can not change there due to backcompat.

# How will things be released, and when?

A Test-Stream dist can be released as soon as the backcompat stuff we no longer wish to carry is removed. It will NOT have Test::More, Test::Builder or Test::Simple namespaces. It will be considered subject to change and somewhat experimental for a period of time yet to be determined, but less than a year.

Test::Compat (or Test::Stream::Builder, or something else) will be part of the dist, and will be the most experimental feature and most subject to change.

A new Test-Simple release will be made that will throw an exception if it sees Test::Stream is loaded before Test::Builder. Documentation will also be updated to reflect that Test-Stream is happening and that authors of new tools should consider using it knowing that once it is stable it will be the new recommended tool. It will also document the restricted subset of the Test::Builder API that will also work with Test::Stream using Test::Compat.

Sometime in the next year (may be extended to a later time period) the Test-Simple and Test-Stream dists will be merged. This will happen when we are content with the state of Test-Stream and do not think it needs any significant churn to be ready as the next base for testing tools. No modifications to Test::More, Test::Builder or Test::Simple will be made in this merger. The original Test-Simple namespaces will be locked to all unnecessary changes.

**Comment by kentfredric** [comment]
> Sometime in the next year (may be extended to a later time period) the Test-Simple and Test-Stream dists will be merged

This is my only present point of contention here, and its mostly because splits/merges are a respectable headache for downstream vendors.

Its not a problem if splits/merges happen prior to vendor replication of this module, but becomes growingly so after the fact.

So I'd like to sort the exact plan there out to be either one of the two in advance and stick with it.

**Comment by exodist** [comment]
I want them to be distinct dists in the experimental stage, I expect significant churn, possibly a release every week, that is not a good idea in the Test-Simple dist. However since after the experimental stage is done we plan to list it as the replacement for Test-Builder, I want it in that dist so it is just as widely available.

How about we document clearly in each module in a note to vendors that in the future the merge WILL happen, and if they make vendor releases they are accepting that fact Possibly encouraging them to make the vendor release a merged release of the 2 cpan dists.

**Comment by kentfredric** [comment]
The problem there is "Vendor" is a group of people, not an individual, and its not a guarantee that the person who made that choice and added it to the tree read it, or considered it, and then communicated it to the rest of the people who can do that.

Its the sort of problem that tends to get noticed (for us at least) sometime after the fact.

I can be as proactive as possible and make sure the rest know what to do when they see this, but there's not much we can do in preparation for this problem.

And it becomes especially complicated when we have to consider that it will potentially become part of perl itself in a future release. I think I've worked out  a strategy we can employ prospectively that will minimize or problems in migration though without needing too much communication fragility.

Its just something that is always messy.

You also have to plan in advance what is going to happen if the version numbers desync, which they will if one has a rapid release cycle. 

I imagine you'll start with very low numbers and then warp them up when they merge?

**Comment by exodist** [comment]
"I imagine you'll start with very low numbers and then warp them up when they merge?"

Yes.

**Comment by kentfredric** [comment]
Memo to myself later because I can't think of a more appropriate place:

```yaml
premerge:
    X: ">=virutal/perl-Test-Stream-$version"        # X module needs virtual Test-Stream $version
    virtual/perl-Test-Stream-$pv: =dev-perl/Test-Stream-$pv # pre-merge virtual needs == cpan package version
postmerge:
    X: ">=virtual/perl-Test-Stream-$version"     # X module needs virtual Test-Stream $version 
    virtual/perl-Test-Stream-$pv: =dev-perl/Test-Stream-$pv   # pre-merge virtual needs == cpan package version
    virtual/perl-Test-Stream-$ppv: =virtual/perl-Test-Simple-$ppv # post-merge virtual needs == test-simple verison
```

**Comment by exodist** [comment]
Just a note on what can be dropped as far as backcompat goes:

$Level (unless compat is loaded)
Lots of the extra loops in context
Monkeypatching
Some of the cruft around subtest (hell, they will be significantly simplified)

**Comment by kentfredric** [comment]
I'd imagine due to the backcompat not needing to support monkey patching, that this statement can be reduced to a discouragement, not a forbidding?

https://metacpan.org/pod/release/EXODIST/Test-Simple-1.301001_110/lib/Test/Builder.pm#MONKEYPATCHING , esp:


> however in the distant future it will be removed. Test::Stream upon which Test::Builder is now built, provides hooks and API's for doing everything that previously required monkeypatching.


I'd imagine ceases to be valid?

**Comment by kentfredric** [comment]
And if so, I'd imagine alternative would be "This is discouraged, and if you find youself needing this, a strong recommendation is to utilize equivalent features in Test::Stream where possible"

**Comment by dagolden** [comment]
> There will be a module, Test::Compat, or Test::Stream::Builder, that will load a very specific and limited backwards compatibility. 

My inclination would be to skip this and don't even try.  Trying to maintain Module::Build::Compat is one of the things that just ground me down as a maintainer.

Having any sort of compatibility shim (or, worse, load-time trickery), has all the legacy support problems *plus* the extra problems introduced by the shim.

I think the only way this succeeds long-term at actually making things better is via a completely separate ecosystem totally unburdened by the past.

**Comment by dagolden** [comment]
> There will be a module, Test::Compat, or Test::Stream::Builder, that will load a very specific and limited backwards compatibility. 

My inclination would be to skip this and don't even try.  Trying to maintain Module::Build::Compat is one of the things that just ground me down as a maintainer.

Having any sort of compatibility shim (or, worse, load-time trickery), has all the legacy support problems *plus* the extra problems introduced by the shim.

I think the only way this succeeds long-term at actually making things better is via a completely separate ecosystem totally unburdened by the past.

**Comment by exodist** [comment]
By limited support I mean things that use $tb->ok/is/diag/note/etc, no support for monkeypatching, messing with state, messing with filehandles, etc. Just the super basics.

This covers a huge amount of Test::* namespace, but we will NOT support things that do anything fancy. If a module wants to work in both then IT bears the burden of maintaining compatibility, not us.

**Comment by kentfredric** [comment]
Getting the load-time shim "right" and such that it won't be prone to abuse will be the trickier part.

But I'm more comfortable with that level of trickery as "Something that will exist for transition purposes only" than the current status with similar ( and worse ) levels of trickery to just make them work together by default.

**Comment by kentfredric** [comment]
MO will, be, I suggest:

- You want new features
- New features require Test::Stream
- Test::Stream and Test::Builder go "bang" together by default
- You throw in your compat module with limited features
- You try get it working like that
- If you need features that are not unlocked by compat, then you have to go full-test-stream
- but if compat works for you, then it works for you, and you file a bug with yourself to get all your dependencies migrated 
- then when your dependencies are migrated, you drop the compat module
