### ISSUE TITLE
Test::Stream $root not initialized when END block runs

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#592]
With Test::Stream 1.301001_110:

```
$ pmvers Test::Stream
1.30100111
Can't call method "concurrency_driver" on an undefined value at .../Test/Stream.pm line 25.
END failed--call queue aborted at /usr/bin/pmvers line 42.
```
My `/usr/bin/pmvers` on Ubuntu 14.04 is exactly the same (except $VERSION) as [`pmvers` from distribution pmtools](https://metacpan.org/source/MLFISHER/pmtools-2.0.0/bin/pmvers).

**Comment by dolmen** [comment]
Simpler test:

```
$ perl -mTest::Stream -e0
Can't call method "concurrency_driver" on an undefined value at /home/omengue/.plenv/versions/5.10.1/lib/perl5/5.10.1/Test/Stream.pm line 25.
END failed--call queue aborted.
```
As `-M` instead of `-m` solves the issue, I suppose that `import` is initializing `$root`.

**Comment by karenetheridge** [comment]
It seems odd that so much code is being run merely from the loading of the module. Is this necessary?

**Comment by exodist** [comment]
much of it is not necessary. I am fixing this along with other issues. this is related to the email I sent perl-qa about the work Test-Stream still needs :-)

**Comment by exodist** [comment]
This has been addressed in the new repo we are using for the Test-Stream components, closing here.
