### ISSUE TITLE
Combination of dev Test::More and latest Test::Stream fails tests on non-threaded 5.8.x

### ISSUE THREAD

**Issue by ribasushi** [Test-More/test-more#594]
```
t/overload_threads......................Can't locate object method "tid" via package "threads" at /home/travis/perl5/perlbrew/perls/5.8.1/lib/site_perl/5.8.1/Test/Stream/Context.pm line 171.
Compilation failed in require at /home/travis/.cpanm/work/1434804418.25281/Test-Simple-1.302004_001/blib/lib/Test/Builder/Module.pm line 5.
BEGIN failed--compilation aborted at /home/travis/.cpanm/work/1434804418.25281/Test-Simple-1.302004_001/blib/lib/Test/Builder/Module.pm line 5.
Compilation failed in require at /home/travis/.cpanm/work/1434804418.25281/Test-Simple-1.302004_001/blib/lib/Test/More.pm line 23.
BEGIN failed--compilation aborted at /home/travis/.cpanm/work/1434804418.25281/Test-Simple-1.302004_001/blib/lib/Test/More.pm line 23.
Compilation failed in require at t/overload_threads.t line 20.
BEGIN failed--compilation aborted at t/overload_threads.t line 20.
dubious
	Test returned status 255 (wstat 65280, 0xff00)
```

This is due to [this check](https://metacpan.org/source/EXODIST/Test-Simple-1.302004_001/t/overload_threads.t#L17) taking place without referencing `$Config{useithreads}` which in turn leaves a stale entry in `%INC` (on any 5.8.x) even though `threads.pm` did not load, which in turn [makes this line](https://metacpan.org/source/EXODIST/Test-Stream-1.302006/lib/Test/Stream/Context.pm#L175) blow up.

Easiest (and most reliable) fix is to check `$Config{useithreads}` within any test file, and only then attempt to load `threads.pm`.

**Comment by exodist** [comment]
Fixed by:
https://github.com/Test-More/test-more/commit/a1c10e2dd4b37bad7f618d04803bb343496f4d15
and
https://github.com/Test-More/Test-Stream/commit/7a4bf2f8b3904d2aebfb1bc8acc8cb7c306eecf9
