### ISSUE TITLE
Test::Tester blows up in the face of a subtest

### ISSUE THREAD

**Issue by autarch** [Test-More/test-more#596]
```perl
use strict;

use Test::Tester;
use Test::More;

my( $premature, @results ) = run_tests(
    sub {
        subtest(
            'Test::Tester should handle this',
            sub {
                ok( 1, 'test 1 is goos' );
            }
        );
    }
);
```

This fails with both the `legacy/master` and `stream/master` branches, but in different ways.

**Comment by exodist** [comment]
This is a known limitation of Test::Tester, in fact it is one of the issues that lead to Test::Stream.

The main problem here is that the way Test::Tester works, and the way Subtests are implemented in legacy code do not play nicely together. The intention is that new code will use Test::Stream::Tester which has more features and support than Test::Tester, and will work even with Test::Builder based tools so long as Test::Stream and the latest Test::Builder is installed.

I do not intend to spend any time enhancing Test::Tester, though I am committed to maintaining it, and fixing anything broken that worked before. That said, if someone submitted a patch to fix subtests in Test::Tester I would happily merge it.

**Comment by autarch** [comment]
Cool, I didn't realize there was a replace for Test::Tester coming as well. I'll close this issue.
