### ISSUE TITLE
cmp_ok($foo, "ne", "") gives the wrong expected value

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#6]
* GC-ID:     [36](http://code.google.com/p/test-more/issues/detail?id=36)
* GC-Labels: Type-Defect, Priority-High, Milestone-Next-Stable
* GC-Status: Accepted
* GC-Attachments: No

-----

* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2009-02-14T21:17:23

What steps will reproduce the problem?
1. $foo = undef; cmp_ok($foo, "ne", "");

What is the expected output?

    #   Failed test at -e line 1.
    #          got: undef
    #     expected: anything but ""

That would be a start, but it loses the fact that this is an "ne" test.  So
this would be better:

    #   Failed test at -e line 1.
    #     undef ne ""

What do you see instead?

    #   Failed test at -e line 1.
    #          got: undef
    #     expected: anything else

-----
* From: [ggvaidya at Google Code](http://code.google.com/u/ggvaidya/)
* Date: 2009-02-20T15:58:55

Is this to be a special case for undef, or should it apply to all 'isnt' 
comparisons? If the latter, should it apply to 'is' comparisons as well?

-----
* From: [schwern at Google Code](http://code.google.com/u/schwern/)
* Date: 2009-02-20T22:24:32

It will occur any time the thing on the left and right are not the same, and yet are
still equal.  Another example is 0 and 0.0.

    $ perl -wle 'use Test::More test => 1; cmp_ok("0", "!=", "0.0")'
    1..1
    not ok 1
    #   Failed test at -e line 1.
    #          got: 0
    #     expected: anything else
    # Looks like you failed 1 test of 1.

We got 0 but we expected 0.0.

The problem with the isnt() diagnostics is that it assumes that on failure what we
got is the same as what we expected.  is() does not have this problem because it
shows what we got and what we expected.

-----
* From: [ggvaidya at Google Code](http://code.google.com/u/ggvaidya/)
* Date: 2009-02-22T09:20:20

Makes sense. 

I've fixed this in http://github.com/gaurav/test-more/tree/issue36, but, since 
'cmp_ok' throws a warning when 'undef' values are used, my new test produces these 
warnings as well. Should I use $SIG{__WARN__} to surpress these warning messages, or 
fix 'cmp_ok' to handle 'undef' correctly? I tried to do the latter, but t/undef.t 
specifically checks for that warning, and I didn't want to break it in case somebody 
depends on it.

-----

**Comment by schwern** [comment]
Test2 has a new and different problem!

```
$ perl -wle 'use Test2::Bundle::Extended; my $foo = undef; cmp_ok($foo, "ne", ""); done_testing'
# Seeded srand with seed '20160814' from local date.
Use of uninitialized value $got in string ne at (eval in cmp_ok) -e line 1.
not ok 1
# Failed test at -e line 1.
# +-----+----+-------+
# | GOT | OP | CHECK |
# +-----+----+-------+
# |     | ne |       |
# +-----+----+-------+
1..1
```

**Comment by exodist** [comment]
ok, the table should show <undef> so that needs to be fixed.

not sure if you were implying the warning was a bug, the warning should be there, and as expected it is warning from the caller. trying to 'eq' against undef is usually a mistake and the warning is good.

**Comment by kentfredric** [comment]
My thoughts after seeing this is the warning aught to be part of the test output so its clear what its attached to.

```
# Failed test at -e line 1.
# +-----+----+-------+ ---
# | GOT | OP | CHECK | NOTES
# +-----+----+-------+ ---
# |     | ne |       | uninitialized value $got
# +-----+----+-------+ ---
```

Or something.

**Comment by kentfredric** [comment]
Also in other cases where there's string overload, you'd probably want some sort of "no-overload" depiction of the terms for clarity.

**Comment by schwern** [comment]
The warning is fine. It's showing two blanks that doesn't help debug the problem. What I would expect to see is something like:

```
# Seeded srand with seed '20160814' from local date.
Use of uninitialized value $got in string ne at (eval in cmp_ok) -e line 1.
not ok 1
# Failed test at -e line 1.
# +-------+----+-------+
# | GOT   | OP | CHECK |
# +-------+----+-------+
# | undef | ne | ''    |
# +-------+----+-------+
1..1
```

**Comment by kentfredric** [comment]
I thought that as well at first, but then I realised maybe that's not really optimal for this table.

Its optimal-ish for this *case*, but when you start getting into escaping, line feeds and UTF8 Characters, forcing it to be displayed in a dumper-esque format might be more trouble than its worth.

Another errant  thought I had was to display a secondary table, and so horrible cases like:

   cmp_ok( undef, 'ne', bless( \%thing, "classname" )) where "classname" has string overloads would do:
```
# +-------+----+---------------------+
# | GOT   | OP | CHECK               |
# +-------+----+---------------------+
# |       | ne |                     |
# +-------+----+---------------------+
# | undef | ne | bless(...,classname)|
# +-------+----+---------------------+
```

Because clearly, neither the first row or the second row of this table is illuminating on its own.

**Comment by exodist** [comment]
I think empty strings, and strings that are only space characters (as in ascii space, not tabs, or other whitespace), should be quoted in the table. any other strings render sanely and I do not want to add quotes.

**Comment by kentfredric** [comment]
How are you going to differentiate between 
```
$expected = q[''];
```
and 
```
$expected = q[];

```

**Comment by schwern** [comment]
```
# +---------+----+-------+
# | GOT     | OP | CHECK |
# +---------+----+-------+
# | "''"    | eq | ""    |
# +---------+----+-------+
```

See https://github.com/Test-More/Test2-Suite/issues/60

**Comment by exodist** [comment]
The test2 related bits of this should be moved to a ticket in Test2::Suite. This ticket only covers cmp_ok in Test::More.
