### ISSUE TITLE
Test::Perl::Critic broken on Test-Simple-1.302007_004 

### ISSUE THREAD

**Issue by kentfredric** [Test-More/test-more#600]
Test::Perl::Critic does some [funky code in `all_critic_ok`](https://metacpan.org/source/THALJEF/Test-Perl-Critic-1.03/lib/Test/Perl/Critic.pm#L90)

The redux of which is as follows:

```perl
use Test::More;
use Test::Builder;

my $TEST = Test::Builder->new();

sub fake {
  $TEST->use_numbers(0);
  $TEST->no_ending(1);
  # ...
  $TEST->done_testing(1); # a computed number of tests from its deferred magic 
}

fake();
```

On stable Test::Simple, this emits "1..1"

On the latest dev release, this emits "1..0" and of course makes prove barf with :

```
xt/author/critic.t .. 
ok - Test::Perl::Critic for "lib/lib/byversion.pm"
1..0
skipped: (no reason given)

Test Summary Report
-------------------
xt/author/critic.t (Wstat: 0 Tests: 1 Failed: 0)
  Parse errors: Bad plan.  You planned 0 tests but ran 1.
Files=1, Tests=1,  3 wallclock secs ( 0.03 usr  0.00 sys +  1.81 cusr  0.60 csys =  2.44 CPU)
Result: FAIL
```

**Comment by kentfredric** [comment]
Just checked:

- This problem has been in place since Test::Simple was built on Test::Stream
- This problem happens with both the newest and oldest Test::Stream versions.

**Comment by kentfredric** [comment]
This bug is still occurring with both the latest dev versions of Test::Simple and Test::Stream.

**Comment by exodist** [comment]
thank you for the ping.

**Comment by kentfredric** [comment]
This appears to fix the issue I had when patched locally.

**Comment by exodist** [comment]
shipped.
