### ISSUE TITLE
1.302012_002 Dies On Missing Argument

### ISSUE THREAD

**Issue by theory** [Test-More/test-more#607]
See [this example](http://www.cpantesters.org/cpan/report/c03e25dc-7f48-11e5-ad69-039f850e5dbe). Does not happen with 1.001014.

**Comment by magnolia-k** [comment]
Fixed at Test-Simple-1.302012_003.

**Comment by exodist** [comment]
Yup. _003 was released because of this problem.

Basically Test::Builder 1.302012_002 had a bug, problem was that the bug caused a no-op. A recent change to Test::Stream made it detect that as an error condition, which exposed the bug in _002, prompting _003's release.

**Comment by exodist** [comment]
51fd6ed03113e0b7ef8d5510586a358dab330baa  is the specific commit with the fix.
