### ISSUE TITLE
Identify a single branch representing current Test-Simple-with-Test-Stream candidate

### ISSUE THREAD

**Issue by rjbs** [Test-More/test-more#609]
*This was an element of the Berlin QAH punch list.*

**Comment by rjbs** [comment]
I believe this is stream/master.  @exodist confirm?

**Comment by exodist** [comment]
correct

**Comment by exodist** [comment]
Due to the name change from Test::Stream to Test2 the branch is now Test2/master

**Comment by exodist** [comment]
For the move to stable that is in progress 'master' now is the branch
