### ISSUE TITLE
Ensure no difference between old and new full TAP output on bleadperl

### ISSUE THREAD

**Issue by rjbs** [Test-More/test-more#610]
*From the Berlin QAH punch list:*

> bleadperl delta smoke with verbose harness output with latest stable and latest dev; review
> line-by-line diff (exodist and ether); should be no substantive changes (outside Test-Simple
> tests themselves)

**Comment by exodist** [comment]
The perl test suite has a LOT of random behavior, and a lot of tests that change significantly based ont eh number of .pm files, and what they are called. Achieving 2 runs with no difference in output is not possible, even between runs of the same exact commit.

I have attempted to work around this using some tools that filter the random noise and reduce the output to parts that matter (TODO, SKIP, OK's, Comments, etc).

https://github.com/exodist/blead_stream_diff

The above repo is where I am recording my tools, my logs, and the results of the comparison. As of the latest commit to the repo I believe I have achieved the goal of this ticket. I eagerly await confirmation from interested parties.
