### ISSUE TITLE
perform a CPAN smokes with Test-Stream candidates

### ISSUE THREAD

**Issue by rjbs** [Test-More/test-more#611]
*From the Berlin QAH punch list:*

> Update CPAN delta smoke: compare test results for all of CPAN with latest stable and
> latest dev (andk, leont, xdg), on Perl verisions 5.8.1, 5.20.2; both with and without threads;
> expect no new changes from previous list of incompatible modules doing unsupported things

**Comment by exodist** [comment]
https://rt.perl.org/SelfService/Display.html?id=127000

patches are attached to that ticket. Alternatively the dists can be found on cpan:

https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test2-0.000011.tar.gz
https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302013_004.tar.gz

**Comment by andk** [comment]
I have started with unthreaded 5.8.1 and will do alternating runs of the two perls. I will *not* cover all of CPAN but use my usual sample (estimated >3000 distros for 5.8.1 and >6000 for 5.20.2). I'll post intermediate results here as my smoker makes progress.

**Comment by andk** [comment]
I just noticed 1.302013005 and 0.000012 have been released. Does that mean to restart the comparison?

**Comment by exodist** [comment]
only if you want to and have time to burn. the changes for those releases are mainly just documentation and renaming modules. not things that should effect the smoking.

I suspect we will want a final smoking much later, for now the results on the version you already started smoking should be sufficient for finding things to fix.

**Comment by andk** [comment]
OK, I'll decide about that later. Thanks for the update!

**Comment by exodist** [comment]
@andk this might be helpful: https://github.com/Test-More/test-more/blob/Test2/master/xt/downstream_dists.list.known_broken

This is a list of distributions which do things too crazy for us to support. They are known breakages that we are ok with as we move forward. Several have chosen to wait until we go stable, then update.

At least one dist on this list has started working again, I have not looked into why. I also do not recall which on right now.

**Comment by andk** [comment]
Test::Builder:Clutch and Test::FileReferenced seem to work

**Comment by exodist** [comment]
@andk New Test2 and Test-More were just released. These should fix the issues you found during the smoking.

**Comment by andk** [comment]
Looks all good to me now. My smoker just finished with ~58000 test runs. The last differences were reported in separate tickets and it seems they all will be resolved outside of Test::Simple. Soooo, that far that means that my smoker found no objection against 1.302013012. github doesn't want my 50 MB logfiles. If anybody wants them, let me know where to upload them, I'll keep them for a while. Feel free to close this ticket now. Or if you prefer to ask further questions or make a new release or whatever, let me be your smoking Berliner.

``` table
| started at          | perl tag   | threaded | longdouble | Test-Simple | Tests | Footnote |
|---------------------+------------+----------+------------+-------------+-------+----------|
| 2016-02-06T14:40:58 | v5.22.1    | undef    | undef      |    1.001014 |  7381 |        1 |
| 2016-02-07T17:52:54 | v5.22.1    | undef    | undef      | 1.302013012 |  7373 |          |
| 2016-02-08T22:55:57 | v5.22.1    | define   | define     |    1.001014 |  7386 |        2 |
| 2016-02-10T08:04:26 | v5.22.1    | define   | define     | 1.302013012 |  7377 |          |
| 2016-02-13T00:03:10 | perl-5.8.1 | undef    | define     |    1.001014 |  7144 |        3 |
| 2016-02-14T04:40:10 | perl-5.8.1 | undef    | define     | 1.302013012 |  7117 |          |
| 2016-02-15T04:20:51 | perl-5.8.1 | define   | undef      |    1.001014 |  7148 |        4 |
| 2016-02-16T08:14:57 | perl-5.8.1 | define   | undef      | 1.302013012 |  7126 |          |

Footnotes

| 1 | circular-require                | issues/632   |
|   | Data-Peek                       | issues/633   |
|   | Store-CouchDB                   | flapping     |
|   | Test-Aggregate                  | known_broken |
|   | Test-DBIx-Class-Schema          | known_broken |
|   | Test-Pretty                     | known_broken |
|   | WWW-Scraper-ISBN-Pearson_Driver | flapping     |
| 2 | circular-require                | issues/632   |
|   | Data-Peek                       | issues/633   |
|   | Plack-Handler-Stomp             | flapping     |
|   | SDL                             | flapping     |
|   | SQL-DB                          | flapping     |
|   | SQLite-More                     | flapping     |
|   | Test-Aggregate                  | known_broken |
|   | Test-DBIx-Class-Schema          | known_broken |
|   | Test-Pretty                     | known_broken |
| 3 | autouse                         | issues/634   |
|   | Data-Peek                       | issues/633   |
|   | Quiki                           | flapping     |
| 4 | autouse                         | issues/634   |
|   | SDL                             | flapping     |
```

**Comment by exodist** [comment]
This ticket is no longer accurate. Right now cpan testers are verifying _009 and _010 before we go stable.
