### ISSUE TITLE
Ensure Test-Stream-based Test-Simple performance is not too changed

### ISSUE THREAD

**Issue by rjbs** [Test-More/test-more#613]
*From the Berlin QAH punch list:*

> Performance benchmarking; while specific workloads will vary, generally a ~15% slowdown on a
> "typical" workload is acceptable
>
> * Add patches to existing bechmarking tools in Test-Simple repo (ether and bulk88)
> * Run benchmarks on at least Linux (exodist) and Windows (volunteer needed)

**Comment by rjbs** [comment]
I ran preliminary testing and found the change in speed well under 10%. I will run again on a published branch, and will ask for Win32 results also.

**Comment by exodist** [comment]
With Test2 (current blead + patch at https://rt.perl.org/Public/Bug/Display.html?id=127000):
Elapsed: 674 sec
u=5.74  s=1.63  cu=328.02  cs=26.11  scripts=2351  tests=758648
make test  342.78s user 29.01s system 54% cpu 11:24.80 total

Without Test2 (current blead)
Elapsed: 642 sec
u=5.70  s=1.49  cu=297.96  cs=24.05  scripts=2316  tests=757832
make test  312.79s user 26.91s system 52% cpu 10:51.91 total

674 - 642 = 32

This means that altering Test::Builder to use Test2 under the hood slows the test suite down by 32 seconds out of ~11 minutes.

**Comment by exodist** [comment]
According to a web based difference calculator this is a 4.8632% difference. This is WELL under the ~15% acceptible.

**Comment by exodist** [comment]
For another comparison I decided to do Moose install:

Legacy:

    cpanm --reinstall Test::More
    [...]
    Successfully installed Test-Simple-1.001014
    time cpanm --reinstall Moose
    [...]
    cpanm --reinstall Moose  82.95s user 6.58s system 101% cpu 1:28.21 total

New:

    cpanm --reinstall --dev Test::More
    [...]
    Successfully installed Test-Simple-1.302013_004
    time cpanm --reinstall Moose
    [...]
    cpanm --reinstall Moose  90.60s user 7.15s system 101% cpu 1:36.41 total

Using a web based difference calculator this shows as:

Difference between V1 = 88.21 and V2 = 96.41 is 8.8831% difference

This is still under the ~15%

Different workloads obviously vary. I do think that Moose and Perl itself are good indicators.

**Comment by exodist** [comment]
.. Might be nice to clarify what type of percentage we are using here? Are we using percentage of difference, or percentage of change?

http://www.calculatorsoup.com/calculators/algebra/percent-difference-calculator.php
http://www.calculatorsoup.com/calculators/algebra/percent-change-calculator.php

These are different. They are also different from some results people have sent me where they simply divide the smaller time by the larger and multiply by 100.

Which type of percentage do we want? at this point all 3 produce results under the ~15%, but by different margins.
