### ISSUE TITLE
is() copes poorly with non-text (binary) strings

### ISSUE THREAD

**Issue by leonerd** [Test-More/test-more#614]
E.g.

    $ perl -MTest::More -E'is("\x01","\x02")'
    not ok 1
    #   Failed test at -e line 1.
    #          got: ''
    #     expected: ''

I'd love this output to read instead

    #   Failed test at -e line 1.
    #          got: "\1"
    #     expected: "\2"

or some variant thereon.

**Comment by leonerd** [comment]
I believe the stringification happens on this line:

https://github.com/Test-More/test-more/blob/legacy/master/lib/Test/Builder.pm#L1025

**Comment by kentfredric** [comment]
I should open a seperate bug, but I note `explain`  is limited the same way, so using it to add clarity in `diag` gets you nowhere.

```perl
use strict;
use warnings;

my @items = (
    "Hello World",         # Normal string
    "Hello\x{A0}World",    # Binary string with 0xA0
    
    # A string with unicode 0xA0 in it, cheating using auto-upgrade
    # by chomping off the >255 char afterwards.
    substr( "Hello\x{A0}World\x{2192}", 0, -1 ),
    "Hello\x{01}World",    # A binary string with 0x01
);

use Test::More;
diag explain \@items;
pass();
done_testing;
```
```tap
# [
#   'Hello World',
#   'Hello World',
#   "Hello\x{a0}World",
#   'HelloWorld'
# ]
ok 1
1..1
```
```
 perl /tmp/annoy.pl |& cat -vET 
# [$
#   'Hello World',$
#   'HelloM- World',$
#   "Hello\x{a0}World",$
#   'Hello^AWorld'$
# ]$
ok 1$
1..1$
```

**Comment by exodist** [comment]
Fixing is() would be a breaking change. However Test2::Tools::Compare has an is() that solves this problem. I am going to close this ticket and recommend switching to Test2
