### ISSUE TITLE
Possible bug in Test::Builder, fix is easy, but might break things

### ISSUE THREAD

**Issue by exodist** [Test-More/test-more#616]
Test::Builder appends all Ok's to a structure it can return via $tb->details. These Ok's have the fields 'ok' and 'actual_ok'. 'actual_ok' is the true/false value passed to $tb->ok, 'ok' is adjusted to be true if the test was run under TODO.

https://metacpan.org/source/EXODIST/Test-Simple-1.001014/lib/Test/Builder.pm#L845

The bug is in subtest handling. When you start a subtest you essentially create a new Test::Builder singleton, and the TODO state is clear int he new one, but it has a field 'parent_TODO' that gets set. This is used to ensure that failures in a subtest when the parent has TODO set do not count as actual failures.

The problem is that parent_todo is not considered when setting the OK's in the details in subtests. That means if a subtest ok fails, and the parent is in todo, the 'ok' and 'actual_ok' are both set to false.

The fix is easy, just change line 845 to look at parent_TODO. However this breaks Test::ClassMoose because it uses details to verify its results. https://metacpan.org/source/DROLSKY/Test-Class-Moose-0.67/t/basic.t#L55

I spoke with autarch about this test since he is the current maintainer. He agrees with me that 'ok' should be true in that test, and that this is probably a bug.

I have not yet figured out what else this may break on cpan, I will try to do that tomorrow.

What I am looking for from cpan-workers:

1) Do you think this is actually a bug, or does it work as you think it should?
2) Even if we all agree it is a bug, can we fix it, or do we need to preserve it to avoid breaking things?

**Comment by exodist** [comment]
Adding an email reply from @karenetheridge 

> The problem is that parent_todo is not considered when setting the OK's in the details in subtests. That means if a subtest ok fails, and the parent is in todo, the 'ok' and 'actual_ok' are both set to false.

Why is this a bug? After all, it's only the top level of TAP that ever matters when it comes to the overall test pass/failure, and a subtest's pass or fail status will be adjusted accordingly for the parent TODO at the *parent's* level. TODOs don't need to propagate downward to all contained subtests.

Further, if we required that TODO state must propagate down to all contained subtests, that means that subtests must always be aware of that upper state -- which rules out any use of separate processes to to create the subtest results, which is conceptually possible (something else, thinking that it is a top-level test, can provide us the TAP, and then we nest it as a subtest into another test -- and this should be possible both with TAP strings and with an event streamer).

**Comment by exodist** [comment]
> Why is this a bug? After all, it's only the top level of TAP that ever matters when it comes to the overall test pass/failure, and a subtest's pass or fail status will be adjusted accordingly for the parent TODO at the *parent's* level. TODOs don't need to propagate downward to all contained subtests.


This bug has nothing to do with TAP. '->details' is used to get a record of all tests that have passed through the Test::Builder instance. These details should accurately reflect if the test was a pass or fail, they do not. By not using parent_TODO here Test::Builder is at the very least being inconsistent with itself. When a failure occurs in a subtest where the parent is todo Test::Builder will send the diagnostics and errors to STDOUT instead of STDERR like it does with any TODO failure. This is the __ONLY__ place where Test::Builder does not account for the parent_TODO on a subtest, and in that way it is being inconsistent if not buggy.
 
> Further, if we required that TODO state must propagate down to all contained subtests, that means that subtests must always be aware of that upper state -- which rules out any use of separate processes to to create the subtest results, which is conceptually possible (something else, thinking that it is a top-level test, can provide us the TAP, and then we nest it as a subtest into another test -- and this should be possible both with TAP strings and with an event streamer).

I can't control TAP from other sources, but as I said, this bug has nothing to do with TAP. This has to do with Test::Builders internal understanding of tests __it__ produced. Outside TAP never has, nor will it ever effect this, they do not appear in the details structure.

**Comment by exodist** [comment]
Added the Test::Stream label as I *accidentally* fixed this in the Test2/Master branch which is how the bug was noticed.

**Comment by karenetheridge** [comment]
My references to TAP were a bit muddled. Let me explain -- I'm trying to differentiate between the state of the individual (possibly nested) test objects, and the eventual data that needs to be conveyed to the user as a result of those tests -- where I used the TAP strings as a shorthand for the latter.

> When a failure occurs in a subtest where the parent is todo Test::Builder will send the diagnostics and errors to STDOUT instead of STDERR like it does with any TODO failure.

This is a good reason to track the parent's state -- provided you're printing out the results of the tests as they are run, which makes sense in the normal case -- but if you're collecting all the tests up and only generating the output (or whatever the result is) at the end, individual test objects don't need to know whether their parent is TODO or not.

For this reason I wouldn't default to communicating parent->child state in the rewrite -- but for the old-school Test::Builder, I'll concede that it's necessary.

I hope this makes more sense.

**Comment by exodist** [comment]
I ran my downstream tests, which means installing every module in https://github.com/Test-More/test-more/blob/Test2/master/xt/downstream_dists.list including all their deps on a virgin perl install + the fix. Test::Class::Moose is the only thing that breaks from fixing this. It is not a test of all cpan/darkpan, but it is a very good list for finding breakages.

I will wait to see if more feedback is received in this ticket, if not then I will patch legacy Test::Builder and cut a trial release for it, after a week or so without complaint I will release it as stable.

**Comment by exodist** [comment]
I looked at this in more detail this morning, and attempted a patch. I was wrong. This is not a bug. details is used to produce the "failed x tests out of y" message, which a subtest needs to output as well. Setting the 'ok' based on parent todo breaks a lot of internals.

I still think it is inconsistent, and not intuitive. But it is not incorrect.
