### ISSUE TITLE
RYBSKEJ/forks-0.36.tar.gz hangs with 1.302013_005

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#617]
I have tried it with several perls and the result always was, with a downgrade to EXODIST/Test-Simple-1.001014.tar.gz I could test forks in under 3 minutes. With 1.302013_005 there was no progress for an hour.

**Comment by exodist** [comment]
https://metacpan.org/source/RYBSKEJ/forks-0.36/t/forks01.t#L36

I suspect this monkeypatching that is at the start of most tests is related. It monkeypatches a private method on Test::Builder. The method it monkeypatches is related to how Test::Builder exits after all tests are complete. In my running of the tests it appears that the test just hangs AFTER the last test runs.

I will keep looking into this. But overriding a private method related to existing the test is kind of crazy. However it looks like the behavior they attempted to add is something Test2/Test-Stream should already have.

**Comment by exodist** [comment]
Aha, I have a fix. Test2::API::test2_no_wait(1)  was added to fix this a long time ago, but at some point it got removed from the Test::Builder code, I think I know when/how. It needs to be run by Test::Builder at compile-time if threads are enabled.

**Comment by exodist** [comment]
Fixed in Test2/master
