### ISSUE TITLE
Data::Dumper usage confuses at least two downstream tests

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#621]
I've found two distros that are confused because Data::Dumper is loaded. They have relied that DD is not loaded. Would you be willing to either write them bug reports that their expectation is unreasonable? Or would you rather go back and load DD more lazily?

The two tests are:

https://metacpan.org/source/BAREFOOT/Debuggit-2.06/t/default_funcs.t#L36

https://metacpan.org/source/SONGMU/L-0.01/t/001_basic.t#L12

HTH && Good night,

**Comment by exodist** [comment]
Fix merged to Test2/master, closing
