### ISSUE TITLE
Test::More::Prefix fails with Test::More 1.302013_005 and later

### ISSUE THREAD

**Issue by eserte** [Test-More/test-more#624]
See http://www.cpantesters.org/cpan/report/6228aac0-b1f8-11e5-b5d2-d9498310ba59 for a sample fail report with _005. I see the same failure with _006.

Bug report for Test::More::Prefix also exists: https://rt.cpan.org/Ticket/Display.html?id=110959

**Comment by exodist** [comment]
This has been known for a while. The dist does things that are not supported moving forward. It was deemed an acceptable breakage.

**Comment by exodist** [comment]
ah, looks like there was actually a fix put in place under the Test::Stream name. Some updating will be necessary, I twill submit a patch to them when I have a chance.

**Comment by exodist** [comment]
There is a ticket on the project, and x-breaks has this info. I also submitted a patch that will fix this. Closing the ticket.
