### ISSUE TITLE
Test::More::subtest has bogus variable assignment and wrong docs.

### ISSUE THREAD

**Issue by kentfredric** [Test-More/test-more#636]
https://metacpan.org/source/EXODIST/Test-Simple-1.302013_012/lib/Test/More.pm#L767-771

Here, the code indicates that `subtest()` only takes two arguments.

And then it forgets that it takes 2 arguments, and passes N-Many arguments.

```perl
sub subtest {
    my ($name, $subtests) = @_;
 
    my $tb = Test::More->builder;
    return $tb->subtest(@_);
}
```

The documentation for `Test::More::subtest` further perpetuates this confusion.

So when one sees somebody in [the wild actually using more arguments](https://metacpan.org/source/PREACTION/Statocles-0.071/lib/Statocles/Test.pm#L240-247), the result is naturally confusion.

https://metacpan.org/pod/release/EXODIST/Test-Simple-1.302013_012/lib/Test/Builder.pm#subtest

Documentation for `Test::Builder::subtest` gives a little context that extra parameters are *args* of some kind, and then says "Check Test::More::subtest", which we previously showed was wrong.

Only when you look past that "No, look somewhere else" do you see:

> subtest also, and optionally, accepts arguments which will be passed to the subtests reference. 

Which is very easy to overlook, partly because of the incredibly awkward grammar.

**Comment by exodist** [comment]
fixed
