### ISSUE TITLE
Installing Test-Tester-0.04 ?

### ISSUE THREAD

**Issue by salvis** [Test-More/test-more#638]
Hi,

I would like to

   perl -MCPAN -e 'install MIME::Parser'

This wants to install Test::Deep (RJBS/Test-Deep-1.120.tar.gz), which in turn wants to install Test::Tester (EXODIST/Test-Simple-1.001014.tar.gz). The latter installs successfully, but then Test::Deep complains:

> Warning: Prerequisite 'Test::Tester => 0.04' for 'RJBS/Test-Deep-1.120.tar.gz' already built but the result looks suspicious. Skipping another build attempt, to prevent looping endlessly.

And later:

> PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/all.t ..................... Can't locate Test/Tester.pm in @INC (@INC contains: /root/.cpan/build/Test-Deep-1.120-32wXAF/blib/lib /root/.cpan/build/Test-Deep-1.120-32wXAF/blib/arch /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/std.pm line 4.
BEGIN failed--compilation aborted at t/std.pm line 4.
Compilation failed in require at t/all.t line 4.
BEGIN failed--compilation aborted at t/all.t line 4.
t/all.t ..................... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run

And finally:

>Result: FAIL
Failed 33/38 test programs. 0/19 subtests failed.
make: *** [test_dynamic] Error 2
  RJBS/Test-Deep-1.120.tar.gz
one dependency not OK (Test::Tester); additionally test harness failed
  /usr/bin/make test -- NOT OK

It seems that Test::Deep (dependency of MIME::Parser) is expecting to get
http://search.cpan.org/~fdaly/Test-Tester-0.04/lib/Test/Tester.pm
rather than
http://search.cpan.org/dist/Test-Simple/lib/Test/Tester.pm

Please -- what can I do to resolve this?

Hans

**Comment by exodist** [comment]
Are you still having this problem?

**Comment by exodist** [comment]
please re-open if you still have a problem.
