### ISSUE TITLE
x_breaks entries have been lost

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#639]
https://metacpan.org/source/EXODIST/Test-Simple-1.302014_001/META.json no longer has the x_breaks entries that document what modules (and versions) that do not work with the Test2 changes. Can these entries be restored?

**Comment by exodist** [comment]
https://github.com/Test-More/test-more/commit/1ede2669e592ffc5c6385f9a4f74f6c6d44f5bf1

**Comment by karenetheridge** [comment]
w00t, thanks!

I forgot to mention earlier that `[Test::CheckBreaks]` will generate for you a .t file (that can never fail; it is informational only) that will check the x_breaks metadata and sing out about any problems it sees. This code should be easily stealable/adaptable for an and-of-tests check as well.

**Comment by jberger** [comment]
except he probably can't use that :-P remember this IS the test library :-D

**Comment by exodist** [comment]
@jberger we probably could. But we aren't because we made our own library so that we could show the messages post-testing in anyone's tests addition to the test suite. Once the breakage library is no longer needed (nothing left broken) we can switch to the module @karenetheridge suggests.
