### ISSUE TITLE
PUNYTAN/PAD-0.04.tar.gz breaks with 1.302014_001

### ISSUE THREAD

**Issue by eserte** [Test-More/test-more#641]
If the latest Test-Simple is installed, then t/02_plugin.t of PAD-0.04 fails:
```
    #   Failed test at t/02_plugin.t line 43.
    #                   ''
    #     doesn't match '(?^:Bad Request)'
    # Looks like you failed 1 test of 1.

#   Failed test 'null path info'
#   at t/02_plugin.t line 44.
# Looks like you failed 1 test of 4.
t/02_plugin.t ........... 
Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by exodist** [comment]
This is actually caused by a minor change to Explain, and is fixable in Test::Builder. This is not a problem with PAD.

**Comment by exodist** [comment]
I have a fix to Test::Builder for this, it should go out in an hour or so after my testing is complete.

**Comment by exodist** [comment]
Uploaded Test-Simple-1.302014_003  which fixes this.

**Comment by eserte** [comment]
Confirmed.
