### ISSUE TITLE
META x_breaks and Test2::API::Breakage disagree

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#644]
With [Test-Simple-1.302014_007](https://metacpan.org/release/EXODIST/Test-Simple-1.302014_007):
- [META.json](https://metacpan.org/source/EXODIST/Test-Simple-1.302014_007/META.json#L51) says in `x_breaks`:
```
"Test::SharedFork" : "<= 0.35",
"Test::Exception" : "<= 0.43",
```
- [Test2::API::Breakage](https://metacpan.org/source/EXODIST/Test-Simple-1.302014_007/lib/Test2/API/Breakage.pm) says: 
```
'Test::Exception'    => '0.42',
'Test::SharedFork'        => '0.34',
'Test::Moose::More'  => '0.025'
```

I have (both before and after Test-Simple install):
- Test::Exception 0.38
- Test::SharedFork 0.29
- Test::Moose::More 0.023

The consequence:
`t/zzz-check-breaks.t` (which reads MYMETA, see #643) says:
```
# You have the following modules installed, which are not compatible with the latest Test::More:
# Installed version (0.38) of Test::Exception is in range '<= 0.43'
# Installed version (0.29) of Test::SharedFork is in range '<= 0.35'
# 
# You should now update these modules!
```
But:
```
$ perl -MTest2::API::Breakage -E 'say for Test2::API::Breakage->report(1)'
 * Module 'Test::Exception' is outdated, we recommed updating above 0.42.
 * Module 'Test::Moose::More' is outdated, we recommed updating above 0.025.
 * Module 'Test::SharedFork' is outdated and known to be broken, please update to 0.34 or higher.
```

I suggest to:
- add an `xt/` test that would check both are in sync
- generate `x_breaks` from Test2::API::Breakage data

**Comment by exodist** [comment]
thanks, I will look into making this stay in sync better.

**Comment by exodist** [comment]
oh, looking into this again, I intentionally left out any module where the only difference is the test suite. Test::Moose::More does not break in any way with Test2, but its test suite does. There is no good reason to upgrade it. On the other hand Test::Exception does have 1 minor feature that does not behave as expected (but does not break things) so upgrading it is recommended.

**Comment by dolmen** [comment]
I still do not understand why META/x_breaks and Test2::API::Breakage are not synchronized.

If they differ on purpose, a comment should be added for each difference in [dist.ini](../blob/master/dist.ini#L31) / `[Breaks]`.

**Comment by dolmen** [comment]
In particular, `[Breaks]` says `Test::Exception = <= 0.43`, but there is no version 0.44 on CPAN so the breakage can't be resolved.

**Comment by dolmen** [comment]
It seems to be an incorrect usage of `[Breaks]` when I compare [dist.ini](../blob/18e3d40b51019cffc6de1049ff59e5f8cc2063ef/dist.ini) with [Test2::Transition](https://metacpan.org/pod/release/EXODIST/Test-Simple-1.302014_007/lib/Test2/Transition.pod#NEED-TO-UPGRADE) for the modules in the `NEED TO UPGRADE` section plus Test::Exception: there is a shift of one version (or a `<=` where is should be `<`) in dist.ini.

Cc: @karenetheridge

**Comment by exodist** [comment]
good find, will fix the version number.

**Comment by dolmen** [comment]
This should be marked as release blocker because in RC9, `t/zzz-check-breaks.t` reports this:
```
# You have the following modules installed, which are not compatible with the latest Test::More:
# Installed version (0.35) of Test::SharedFork is in range '<= 0.35'
# 
# You should now update these modules!
# You should also see Test2::Transition!
```

**Comment by exodist** [comment]
I don't think this alone constitutes a release blocker, nothing is actually broken, everything still installs and works.

That said there have been enough version mismatches fixed, and a shared memory leak fixed, so I do think a new dev release and a delay to the stable release is warranted.

I will put put a new dev release today, and bump the release out to a week from today, Tuesday may 10'th which happens to be my birthday :-)

**Comment by exodist** [comment]
I believe this is now fixed in master. Please confirm. I intend to release _010 today.

**Comment by dolmen** [comment]
Fixed in _010.
