### ISSUE TITLE
Makefile.PL should detect upgrade_required modules and declare them as prereq

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#645]
About Test-Simple-1.302014_007:
`Makefile.PL` should detect if modules from [Test2::API::Breakage::upgrade_required](https://metacpan.org/source/EXODIST/Test-Simple-1.302014_007/lib/Test2/API/Breakage.pm#L26) are installed and need to be upgraded, and add them to `PREREQ_PM` if necessary.

**Comment by haarg** [comment]
This will lead to circular dependencies.  There isn't currently any sane way to do this unfortunately.

**Comment by exodist** [comment]
?Yeah, unfortunately this problem is not really solvable, closing.

**Comment by dolmen** [comment]
So I'm thinking about writing a dzil plugin that will upgrade the prereqs of my own dists using information from Test2::API::Breakage...

**Comment by karenetheridge** [comment]
> So I'm thinking about writing a dzil plugin that will upgrade the prereqs of my own dists using information from Test2::API::Breakage...

Please be *very* careful with this, as downstream damage could be done. (e.g. lots of trial releases first!)

Also note that this information is available in `x_breaks`, and Dist::Zilla::Plugin::Test::CheckBreaks exists to check this data during test time... I've been working on a plugin to insert code into Makefile.PL to do a similar check, but it's been blocked on improvements to MakeMaker::Awesome and DynamicPrereqs (which are mostly finished now thanks to QAH, so I should dust that off).
