### ISSUE TITLE
t/zzz-check-breaks.t should suggest to read Test2::Transition

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#646]
If at least one upgrade is suggested by t/zzz-check-breaks.t, it should also tell the user to read [Test2::Transition](https://metacpan.org/pod/release/EXODIST/Test-Simple-1.302014_007/lib/Test2/Transition.pod#UPGRADE-SUGGESTED).

**Comment by exodist** [comment]
good idea! Will do.
