### ISSUE TITLE
Hide private modules from PAUSE indexing

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#647]
Some packages are implementation details. Not indexing them now will avoid problems later if ever they will be removed from the distribution.
Those seems to be clearly private as they have no POD and did not exist in the old Test-Simple:
- Test::Builder::Formatter
- Test::Builder::TodoDiag

**Comment by exodist** [comment]
I intend to add pod for those modules. I would prefer to keep them indexed, thank you for bringing it to my attention, will fix.
