### ISSUE TITLE
require Test::Builder after plan fails

### ISSUE THREAD

**Issue by plicease** [Test-More/test-more#648]
Trying to load `Test::Builder` after plan blows up.  This is probably a nonsensical thing to do directly.  However, when I was converting a module from `Test::Builder` to `Test2::API` I found that it was requiring a module which then use'd Test::Builder.  Since the calling module wasn't using `Test::Builder` anymore it blew up in the same way as this minimal test below.  This may be a case of user error, in which case I already have a fix in the module in question.

```perl
use strict;
use warnings;
use Test2::Bundle::Simple;
# use Test::Builder; # <-- makes it work

plan 1;

require Test::Builder;

ok 1;
```

```
iscah% prove -v foo.t 
foo.t .. 
1..1
Formatter Test::Builder::Formatter loaded too late to be used as the global formatter at /home/ollisg/.perlbrew/libs/perl-5.24.0-RC2@dev/lib/perl5/Test/Builder.pm line 37.
Can't locate object method "set_no_header" via package "Test2::Formatter::TAP" at /home/ollisg/.perlbrew/libs/perl-5.24.0-RC2@dev/lib/perl5/Test/Builder.pm line 1146.
Compilation failed in require at foo.t line 7.
# No tests run!
# Looks like your test exited with 255 after test #0.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report
-------------------
foo.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.03 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
iscah% which_pm Test::Simple
Test::Simple         1.302014_007 /home/ollisg/.perlbrew/libs/perl-5.24.0-RC2@dev/lib/perl5/Test/Simple.pm
Test::Simple         1.001014   /home/ollisg/perl5/perlbrew/perls/perl-5.24.0-RC2/lib/5.24.0/Test/Simple.pm
```

**Comment by exodist** [comment]
Test::Builder really does need to be loaded before the first event (plan is the first event) for it to put everything it needs in place. That said I can probably make this specific case a bit more forgiving, or at least provide a better error message.

**Comment by plicease** [comment]
Understood.  Now that I know, this is easy to live with, but as you say a better diagnostic could probably save someone some time once T2 and Test::Builder code starts to mix more.
