### ISSUE TITLE
"This is not a supported configuration, you will have problems."

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#650]
http://www.cpantesters.org/cpan/report/626f1aa6-0ed6-11e6-bd5c-55d09e4cbc8b

This started on those among my smokers that decided to upgrade to 0.000043.

Not sure what I should do now, looks like "I will have problems" ;)

**Comment by exodist** [comment]
Oops. That shows 2 problems. The version number is mangled, and obviously we don't want this message until after they are bundled. I will fix this as soon as I can get to a computer. Not a problem for the dev stuff, just the Test2 tarball.

**Comment by exodist** [comment]
new Test2 tarball up that fixes the version number and the message.

**Comment by exodist** [comment]
problem was that the message was backported from the Test-Simple dev releases, it should not have been.
