### ISSUE TITLE
POD for lib/Test2.pm needs an update

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#654]
The documentation for `Test2` (`lib/Test2.pm`) needs a major update:
- The *Getting started* section talks about `Test2::Suite` but that page doesn't exist
- The *Namespace layout* section talks about namespaces which are so far empty or non-existing. For example I see nothing in `Test2::Tools::` in this distribution.

**Comment by exodist** [comment]
This document is to explain the Test2 ecosystem, and how to structure Test2 specific tools that people write.

Most of these namespaces do actually exist, but inside the Test2-Suite distribution, not Test2 itself.

This document is not intended to be Test2+Test-Simple exclusive, it is supposed to cover things even beyond this base distribution. That said I need to make that more clear if this misunderstanding is possible. I will work on clarifying the document.
