### ISSUE TITLE
[PATCH] fix some spelling mistakes

### ISSUE THREAD

**Issue by gregoa** [Test-More/test-more#657]
In Debian we are currently applying the following patch to
Test-Simple.
We thought you might be interested in it too.

    Description: fix some spelling mistakes
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-05-10
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-simple-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by karenetheridge** [comment]
Maybe it's time this distribution got a spelling test :)
