### ISSUE TITLE
[PATCH] fix POD syntax

### ISSUE THREAD

**Issue by gregoa** [Test-More/test-more#658]
In Debian we are currently applying the following patch to
Test-Simple.
We thought you might be interested in it too.

    Description: fix POD syntax
     add missing =back
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-05-10
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-simple-perl.git/plain/debian/patches/pod-syntax.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by karenetheridge** [comment]
...and got a pod syntax test too :)
