### ISSUE TITLE
"examples" and "Examples" directories both exist

### ISSUE THREAD

**Issue by kentfredric** [Test-More/test-more#660]
Not a huge deal.

But as vendor side, we have an option exposed to end-users where "examples" can be installed to the OS for later perusal, and that's how I happened to notice this, in working out if any such directories were suitable :)

**Comment by exodist** [comment]
https://github.com/Test-More/test-more/commit/3ccd7105a71723e0f8563fca2bdf3094d5dcfef0

leaving open until a dev release on cpan has the change.

**Comment by exodist** [comment]
this is in a dev release
