### ISSUE TITLE
no documentation of what's actually new/better than Test::Builder

### ISSUE THREAD

**Issue by wchristian** [Test-More/test-more#663]
https://metacpan.org/pod/Test2 mentions "completely refactoring it, adding many new features and capabilities", but does not mention any new features or capabilities. Please add at least a rudimentary list. (Considering the recent release speed is preferable over completeness.)

**Comment by petdance** [comment]
This is why I djd this interview w/@exodist.  Maybe it can be a start for whatever doc needs to come out of this.

http://perlbuzz.com/2016/05/30/all-about-the-new-test2-framework-and-how-it-will-help-your-tests/
