### ISSUE TITLE
Can you provide documentation or a link to documentation  for  Test2::Formatter ? 

### ISSUE THREAD

**Issue by l2trace** [Test-More/test-more#687]
Hopefully it provides a way to decorate the response from the the ok.

**Comment by exodist** [comment]
If your goal is to "decorate" the otherwise normal TAP output, then you probably want to subclass https://metacpan.org/pod/Test2::Formatter::TAP

**Comment by exodist** [comment]
https://metacpan.org/pod/Test2::Formatter  tells you how to write a new formatter

https://metacpan.org/pod/Test2::Formatter::TAP  is the main formatter, if you just want to make alterations to the TAP output you should subclass this.
