### ISSUE TITLE
[Regression] Thread test event order lost on T::B 1.3x

### ISSUE THREAD

**Issue by ribasushi** [Test-More/test-more#693]
```
perl -Mthreads -MTest::More=no_plan -e '
  ok 1, "something $_ local" for (1..15);
  threads->create(sub {
    ok 1, "something $_ nonlocal" for (1..15)
  })->join
'
```

The simple program above produces expected `1~15` runs on `1.001014`, but completely loses event order on current stable.

**Comment by exodist** [comment]
I do not consider this a bug. All the results come in and are seen in the TAP output. This change was a conscious decision when picking the new threading/multi-proc mechanism.

This is not likely to introduce any bugs or break anything. Is this report because you have a pre-existing test somewhere that does break from the re-ordering?

I am open to feedback and a civil discussion on this issue. My mind can be changed by compelling facts :-).

**Comment by exodist** [comment]
actually, looks like the problem specifically is the order of events with in the subtest, not the order of events from multiple concurrent subtests. I misunderstood the request initially.

I do think this is solvable, and it would be fairly trivial to do so.

**Comment by ribasushi** [comment]
> I do not consider this a bug.

Sigh...
```
perl -Mthreads -MTest::More=no_plan -e '
  threads->create(sub {
    ok(
      $_ % 42,
      "$_ now how do I correlate the failure with its surrounding PASSes? (hint: line numbers can not help me)"
    ) for ( 1 .. 1000 )
  })->join
'
```
> I am open to feedback and a civil discussion on this issue.

What compelled you to word this sentence exactly this way? Have you ever witnessed me being non-civil / abusive / unfair towards you or anyone else?

**Comment by ribasushi** [comment]
> actually, looks like the problem specifically is the order of events with in the subtest,

Didn't see this reply before I wrote mine. Note - subtests do not play any role here (see my second example)

**Comment by exodist** [comment]
My comment was specifically to make it clear I was not closing the issue and taking a hard "won't fix" stance. The part about civility was not directed at you.

s/subtest/thread/, sorry.

As my second comment stated, I misunderstood the ask here (I thought the for loop was outside the thread, spawning several threads). The ask is actually correct, the events should be ordered, and I will fix it.

**Comment by haarg** [comment]
It also appears that the results from the thread are buffered until the thread is finished.  Older Test::More would output the results as they were generated.

**Comment by exodist** [comment]
Results are not buffered, though this specific test makes it look like they are. That said the mechanism for threading/multi-proc has changed. Test::Builder did not support multi-proc directly, and it supported threads using locking and shared data structures. The new mechanism is to have each thread/proc write events as files in a shared directory. The main process culls these files and renders them. Culling happens in 3 ways:

1. Parent thread gets a context.
2. Test directly culls
3. Parent thread is done, so it waits/culls

In this case the parent thread has nothing to do, so it waits and culls making it appear buffered.

**Comment by exodist** [comment]
I have a fix for this in a branch. Right now I am running a gauntlet of downstream tests to insure nothing is broken. Assuming all my tests are good I will mint a TRIAL release, assuming that also finds no issues I will create a stable release with it some time next week.

**Comment by exodist** [comment]
A -TRIAL release was made with a fix. Assuming nothing is broken I plan to release it as stable next week.

**Comment by ribasushi** [comment]
The test for this issue `693_ipc_ordering.t` is causing segfaults on older perls (<= 5.8.7). The easiest solution would be simply skipping on `"$]" < 5.008008` as the tested changeset is not perl-version-dependent (although `select( undef, undef, undef, 0.2 )` may be all you need to avoid the crash).

**Comment by ribasushi** [comment]
Sample failure if needed: https://travis-ci.org/dbsrgits/dbix-class/jobs/142004312#L1624-L1636

**Comment by exodist** [comment]
Thanks, applied a fix and just uploaded a new TRIAL

**Comment by ribasushi** [comment]
This does pass on my end now.
