### ISSUE TITLE
Ok - '#' and "\n" should be allowed

### ISSUE THREAD

**Issue by exodist** [Test-More/test-more#710]
'#' and "\n" were forbidden due to the TAP standard... But the event system in Test2 is supposed to be decoupled from TAP, so there is no good reason to disallow them at the Test2::Event::Ok level.

Both should be allowed, and Test2::Formatter::TAP (and Test::Builder::Formatter) should decide what to do with them as far as TAP goes.

Ideas for formatters:

For starters the Test::Builder::Formatter MUST preserve backcompat, so it should do what Test::Builder has always done and escape '#' with a single escape, and turn extra lines from a test description into comments.

What do we want to do with Test2::Formatter::Tap?

* Replace newlines with space?
* Make extra lines in description into comments?
 * Indent them by 5/9 characters? (length("ok - " or "not ok - "))
* Strip '#'?
* Replace '#' with space?
* Replace '#' with a unicode variant?
 * Only in utf8 mode?
* Escape '#' with a slash?
* Escape as '\\\#' (@leont?)
* Other?

**Comment by Leont** [comment]
> Escape as '\#' (@leont?)

Test::Harness will accept any non-newline character as long as it is escaped, so escaping both # and \ should be fine (escaping only the former leads to rt.cpan.org#106616).

> Replace newlines with space?

To me it kind of makes sense to escape them as a literal '\n' (as that leads to the least loss of information), but that may be because I arrived here via the above.

**Comment by exodist** [comment]
@leont, hmm it seems to have stripped some characters. I originally intended that to say escape ```#``` as ```\\\#``` does that look correct?

**Comment by schwern** [comment]
* Replace newlines with space?
* Strip '#'?
* Replace '#' with space?

-1 for anything that loses information.

* Make extra lines in description into comments?

+1

 * Indent them by 5/9 characters? (length("ok - " or "not ok - "))

+2 That might turn out to look pretty good. Don't forget the number!

* Replace '#' with a unicode variant?

-1

 * Only in utf8 mode?

+1

* Escape '#' with a slash?

+1

* Escape as '\\\#' (@leont?)

I'm not sure what this means.

* Other?

I think you covered all the solutions I know of.

**Comment by schwern** [comment]
In my experience, newlines in names are rarely deliberate. Usually it's because you write something like this...

    ok $stuff, "we got '$stuff'";

...and sometimes `$stuff` has a newline in it.

So I'm less concerned about it being formatted really nice. I'm more concerned that it not generate an error.

**Comment by exodist** [comment]
ok, I re-read the info from @leant, including rt 106616.

I see now, so the problem is not that Test::Builder escapes ```#``` as ```\#```, the problem is that it does that BUT does not escape ```\``` to ```\```

So ```my # is prefix by a '\'``` should be escaped into ```my \# is prefixed by a '\\'```, wheras Test::Builder escapes it to ```my \# is prefixed by a '\'```. In other words we use ```\``` as an escape character, but then do not escape literal ```\``` characters.

So, I think the solution to that is to escape ```\``` into ```\\```, which I think is what @Leont sugested, and I think that is a change we can make to Test::Builder.

I think we can also apply this escaping to Test2, cause at this point it appears sane to me. That would also make Test2 and Test::Builder consistent, removing some divergent logic.

**Comment by exodist** [comment]
Also, this change should be formatter level, not event level. Non-TAP formatters should not receive test names already escaped like this.

**Comment by exodist** [comment]
See #711 this "fix" breaks 2 modules that live pretty high upriver. The Test2 portion of the fix is safe, but the Test::Builder part is not.
