### ISSUE TITLE
Test::Tester::Delegate lacking can

### ISSUE THREAD

**Issue by haarg** [Test-More/test-more#725]
Test::Tester::Delegate uses AUTOLOAD to delegate to a different object, but it doesn't implement can.  This prevents checking for the existence of methods, which is a problem when you are trying to compatible with a wide variety of Test::Builder versions.

**Comment by exodist** [comment]
I will accept patches/pr's that fix this. However I do not personally have time to work on this, specially since I consider Test::Tester to be discouraged in favor of newer tools.
