### ISSUE TITLE
Compile time errors hidden with T2 + M::B + T2::Plugins::NoWarnings

### ISSUE THREAD

**Issue by toddr** [Test-More/test-more#729]
I have vastly simplified this to show the problem that came up today.

``` perl
#!perl

use strict;
use warnings;

package foo;
use Test::Builder;

package main;

use Test2::Bundle::Extended;
use Test2::Plugin::NoWarnings;

splice(@$array_var, 3 1);
my $array_var = [qw/a b c/];
ok(1, "abc");

done_testing();
exit;

```

If you run this program, you get:
``` 
release() should not be called on context that is neither canon nor a child at /usr/local/lib/Test2/API.pm line 179.
```

What's weird is if you comment off T::B or T2::NoWarnings, you get:
```
$>perl -cw t/test.t
Number found where operator expected at t/test.t line 14, near "3 1"
	(Missing operator before  1?)
Global symbol "$array_var" requires explicit package name (did you forget to declare "my $array_var"?) at t/test.t line 14.
syntax error at t/test.t line 14, near "3 1"
t/test.t had compilation errors.
```

**Comment by toddr** [comment]
The faulty line in my case was doing a splice prior to declaring @$array_var.

**Comment by autarch** [comment]
This might be a bug in `Test2::Plugin::NoWarnings`.

**Comment by autarch** [comment]
I can work around this quite easily in the plugin by adding the `$SIG{__WARN__}` hook inside an `INIT` block, which I think is a good change. That said, this may _also_ be a bug in the Test::Builder code as well.

**Comment by exodist** [comment]
I have simplified it even further:

```perl
use strict;
use warnings;
BEGIN { require "t/tools.pl" };
use Test2::API qw( context_do );

$SIG{__WARN__} = sub {
    context_do {
        shift->send_event('XXX', 'message' => "Got Warning: $_[0]");
    }
    $_[0];
};

my $array_var = [];
eval 'splice(@$array_var, 3 1)';
my $err = $@;
like(
    $err,
    qr/syntax error/,
    "Got expected error"
);

done_testing();
```

which gives:

```
not ok 1 - Got expected error
1..1
# Failed test 'Got expected error'
# at t/Legacy_And_Test2/hidden_warnings.t line 16.
# Value: release() should not be called on context that is neither canon nor a child at /home/exodist/projects/Test-More/lib/Test2/API.pm line 179.
# Does not match: (?^:syntax error)
```

**Comment by exodist** [comment]
Please note that I am sending an XXX event (not valid) if I switch that to a Note event it works fine. My system doesn't have a Warning event installed

**Comment by exodist** [comment]
ok, I figured out *A* problem.

`ctx->throw` will release the context
`context_do` will release the context, but will also passes the ctx into an eval intercepting the throw

Thus we have a double release.

I have a fix in 0769cff188e117dc213013ef13a108418b45c1e4

I am not sure if this fixes the original problem, but it does fix a problem, I will continue to investigate.

**Comment by exodist** [comment]
I can confirm this fix also fixes the example provided by @toddr at the top... though I am not sure why. And yes I am using the old un-patched version of Test2::Plugin::NoWarnings.

**Comment by exodist** [comment]
oh, I figured it out. The reason is because this warning handler squashes the old $@ and replaces it with the double release.

Order of events:

- $@ = 'Global symbol ...'  # The error we want
- A warning fires from somewhere
- context_do localizes $@ by obtaining a context
- context_do calls ->release, which should restore $@
- release fails, replacing $@

My fix makes it so that release does not fail, and $@ is restored properly allowing us to see the original message.

**Comment by exodist** [comment]
So, if I add a hook to print the warning, it becomes a little more clear what is happening here:

```perl
use strict;
use warnings;

package foo;
use Test::Builder;

package main;

use Test2::Bundle::Extended;
use Test2::Plugin::NoWarnings;
use Carp qw/longmess/;

BEGIN {
    my $err = $SIG{__WARN__};
    $SIG{__WARN__} = sub {
        print STDERR longmess("Warning!!!! $_[0]");
        $err->($_[0]);
    };  
}

splice(@$array_var, 3 1); 
my $array_var = [qw/a b c/];
ok(1, "abc");

done_testing();
exit;
```

```
Warning!!!! Number found where operator expected at test.pl line 21, near "3 1"
 at test.pl line 21.
Could not load event module 'Test2::Event::Warning': Global symbol "$array_var" requires explicit package name (did you forget to declare "my $array_var"?) at test.pl line 21.
BEGIN not safe after errors--compilation aborted at /home/exodist/perl5/perlbrew/perls/main/lib/site_perl/5.24.0/Test2/Event/Warning.pm line 3.
Compilation failed in require at /home/exodist/projects/Test-More/lib/Test2/API/Context.pm line 351.
 at test.pl line 17.
```

`3 1` is triggering a warning, which then causes Test2::Event::Warning to need to be loaded, this fails, and it looks like it blames the exception from the test file???

If I preload Test2::Event::Warning things work as expected.

----


At first I thought this was a problem with try or require, but it looks like nothing I do can prevent it from blaming the test.pl syntax error on the module load failure. I suspect global phase/gc issues.

In any case, we are no longer masking the necessary information.

@autarch I would recommending pre-loading the warning event in NoWarnings to avoid this issue. I will release this fix after plenty of cpan-testers results verify it (trial incomming)
