### ISSUE TITLE
`use_ok` does not duplicate the warnings that are in the caller's scope

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#736]
This is not a new bug; it has existed forever probably.

use_ok constructs a new scope in the namespace of the caller, but it doesn't copy the warnings that were in effect in the caller. This means that warnings can be emitted while loading the module that a user may want to disable (e.g. the 'deprecated' category), but there is no way to turn them off.

That is, this should work, without warnings:

```
# in Foo.pm:
package Foo;
warnif('deprecated', 'Foo is deprecated; use Bar instead');

# in foo.t:
use strict;
use warnings;
use Test::More;
no warnings 'deprecated';
use_ok('Foo');
```

...but it doesn't, because `use_ok` doesn't copy the warnings that were in effect in foo.t

You can resolve this by pulling out the warning bits from `caller()`, as done in Eval::WithLexicals::WithPersistence.

**Comment by exodist** [comment]
https://github.com/exodist/Importer/blob/master/lib/Importer.pm#L647 has a fully fleshed out example of setting warnings from caller as an example.

**Comment by exodist** [comment]
should probably also make sure `ok.pm` has similar considerations, it may defer to use_ok under the hood, so it may get them for free.
