### ISSUE TITLE
SysV IPC can cause SIGSYS

### ISSUE THREAD

**Issue by jhi** [Test-More/test-more#738]
While working on getting bleadperl working well with netbsd-vax, many of the Test-Simple tests failed, not just by failing, but crashing Perl hard.  On closer inspection these were all

`Bad system call (core dumped)`

and that means `SIGSYS`, which can happen at least in the *BSD if the SysV IPC has not been configured to the kernel.

This seems to be caused by `lib/Test2/API/Instance.pm` using the `shm*` interfaces without being prepared for the `SIGSYS`.  I am testing a patch for this, and will report back once verified.

**Comment by exodist** [comment]
the shm stuff is an optional optimization. if necessary you can disable it
conditionally by platform (as a patch) if it cannot be made to work.

**Comment by jhi** [comment]
I will use the same pattern as the core tests (and indeed SysV-IPC in CPAN tests) use to soft-fail in this case.

**Comment by jhi** [comment]
Patch attached.  Seems to fix the SIGSYS issue.

So this is not something that should/could be controlled by platform as such, it is more a kernel config issue.  The operating system supports the SysV IPC, and that's why Perl has detected that the feature is supported; but the kernel running has not been configured to enable the feature.  In other words: this needs to be detected in runtime.

(Possibly related issue while eyeballing the use of the `shm*`:  in the `sub enable_ipc_polling` should this line

```            return $_[0]->{hub}->cull unless $self->{+IPC_SHM_ID};```

be instead

```            return $_[0]->{hub}->cull unless defined $self->{+IPC_SHM_ID}; ```


[0001-d_shm-is-not-enough-for-robust-does-SysV-IPC-check.patch.txt](https://github.com/Test-More/test-more/files/574217/0001-d_shm-is-not-enough-for-robust-does-SysV-IPC-check.patch.txt)

**Comment by Leont** [comment]
This behavior is sounds weird if you ask me, failing the syscall with ENOSYS would be way more helpful. Which syscall is failing exactly, and with what error? I note that the `shmget`'s return value is not checked for failure. Could that be involved in this issue?

**Comment by jhi** [comment]
Any of the shm*() does that, but of course most importantly shmget().

Obviously the BSD kernel devs didn't ask you.  I didn't come up with the behavior.  That's just how it is.

Take a look at t/io/shm.t or cpan/IPC-SysV/t/ipcsysv.t in blead.

Also: http://web.mit.edu/freebsd/head/tools/regression/sysvshm/shmtest.c

**Comment by Leont** [comment]
IMO it'd be cleaner to ignore the SIGSYS and deal with ENOSYS, assuming that works.

**Comment by jhi** [comment]
That works, too.  Patch alternative attached.

[0001-d_shm-is-not-enough-for-robust-does-SysV-IPC-check.patch.txt](https://github.com/Test-More/test-more/files/574338/0001-d_shm-is-not-enough-for-robust-does-SysV-IPC-check.patch.txt)

**Comment by Leont** [comment]
That looks much better to me

**Comment by exodist** [comment]
Do we know where exactly the sigsys is being triggered? Specifically I am wondering if I can move the `local $SIG{SYS}` into the top of the try block inside that method?

**Comment by Leont** [comment]
Yeah, moving it into the try block sounds sensible.

**Comment by jhi** [comment]
What Leon said.
