### ISSUE TITLE
Remove Test2::Event::Generic?

### ISSUE THREAD

**Issue by schwern** [Test-More/test-more#752]
Test2::Event::Generic adds complexity to the formatters. In addition to handling all the events, they need redundant code to handle Generic events which have some of the methods of other event types, but not all of them. This makes it difficult to make formatter event handling consistent.

`Test2::Formatter::TAP->event_other` is a good example. It has code redundant with `event_plan`, `event_ok`, and `event_diag`, but slightly different. A change to plan or ok or diag handling has to be done in multiple places. I'm running into this problem fixing #751.

I expect 3rd party formatter authors will just forget to handle Generic events.

The Generic docs justify it with "This is useful if you have need for a custom event that does not make sense as a published reusable event subclass" but there's already plenty of ways to make an event subclass and not publish it.

I doubt anyone is using them, and they haven't been touched since their initial commit. Can we just delete them and the redundant formatter code to handle them?

**Comment by exodist** [comment]
This is a move in the opposite direction I am planning.

The biggest mistake made in the Test2 transition was modeling the event system on TAP. I started with several events, all of which had a 1-to-1 relationship with TAP. The TAP formatter then worked by checking the type and using type-specific logic.

The correct thing to do, and what I am moving towards is having an "event API", Formatters should then make use of the api to decide how to render any event without caring about the type (IE how it is blessed).

The 'Generic' even is a good representation of the API, as is the base event type.

The TAP formatter still has the type conditions for the common types, and that is probably going to stay as it allows for performance optimizations that keep Test2+Test::Builder fast. If removing duplication was the goal then I would remove all the type conditioning logic and instead just have it use the 'other' logic to render all events, but I suspect that would be a performance drain.

**Comment by schwern** [comment]
So there's one event type and it checks its capabilities? That might work out, but right now Generic doesn't have all the information the other events do. What I'm running into right now is Generic doesn't now about pass vs effective_pass.

Since it's unused and isn't being worked on, can we get rid of it until it's being actively developed? Or ignore it until then and rip the code out of the TAP formatter? Having two competing systems, one only partially completed, makes things complicated. We don't even have a second real formatter to exercise the event system with.

**Comment by exodist** [comment]
If the event API is not complete then it should be extended.

The Generic event was not added in case it was needed, it was added when it was needed. A third party module (Cannot remember which one, I different author wrote it) uses it.

The Generic event is also not the only one that the formatter needs to account for. There are now lots of event types out there that implement the event API to do things, the formatter should be able to handle any event that comes through using the event api. If we removed everything related to checking the event type the 'other_event' handler should still do everything right with all event types.

It sound like the main problem right now is that the 'other_event; handler does not in fact handle the builtin event types, and that is what we should fix.

**Comment by exodist** [comment]
Also, the default event types are not going to go away. The idea is not to have just a single 'event' class and have everything use it. The idea is to make a common full-capability interface all Event::* objects can/must implement that allows formatters to universally support them.

Event::Ok is not going to go away, but any other event type should be able to duplicate its functionality using only the common event API, that is methods all formatters will expect an event to have, the ones the base class specifies.

Currently the base class has been given methods that I *thought* would accomplish this, but it appears you are having issues because it does not.

To really get this you need to think of the 'other_event' handler as the actual formatter logic, and all the type specific handlers as optimizations that do not need to be there for it to work, but are there for performance.

**Comment by exodist** [comment]
This conversation has stalled if nothing else. I have no plans to remove the Generic event, I intend to maintain it.
