### ISSUE TITLE
Unknown events in a buffered subtest are ignored by the TAP formatter

### ISSUE THREAD

**Issue by autarch** [Test-More/test-more#776]
This happens because of this line in the `event_tap` method, which is used to turn a buffered subtest's events into TAP:

```perl
    my $converter = $CONVERTERS{ref($e)} or return;
```

This differs from `write`, which will use `event_other` to format these events. Is there any reason not to use the same default here?

**Comment by exodist** [comment]
Is this still a problem? The TAP formatter had some significant changes recently, The line in question no longer exists.

**Comment by autarch** [comment]
Fixed in ... some version or other.
