### ISSUE TITLE
Test::Tester cannot test subtests.

### ISSUE THREAD

**Issue by Abigail** [Test-More/test-more#782]
use Test::Tester;
    use Test::More;

    run_tests sub {subtest Foo => sub {pass}};

This results in

    # Subtest: Foo
    Can't call method "top" on an undefined value at /opt/perl/lib/site_perl/5.26.0/Test/Builder.pm line 45.
    A context appears to have been destroyed without first calling release().
    Based on $@ it does not look like an exception was thrown (this is not always a 
    reliable test)

    This is a problem because the global error variables ($!, $@, and $?) will not be restored.
    In addition some release callbacks will not work properly from inside a DESTROY method.

    Here are the context creation details, just in case a tool forgot to call release():
      File: /opt/perl/lib/site_perl/5.26.0/Test/More.pm
      Line: 807
      Tool: Test::Builder::subtest

    Cleaning up the CONTEXT stack...
    A context appears to have been destroyed without first calling release().
    Based on $@ it does not look like an exception was thrown (this is not always a 
    reliable test)

    This is a problem because the global error variables ($!, $@, and $?) will
    not be restored. In addition some release callbacks will not work properly from
    inside a DESTROY method.

    Here are the context creation details, just in case a tool forgot to call
    release():
      File: /tmp/foo
      Line: 4
      Tool: Test::More::subtest

    Cleaning up the CONTEXT stack...
    # Test ended with extra hubs on the stack!

**Comment by autarch** [comment]
I wonder if Test::Tester could be rewritten to use the Test2 event system. What it does right now is pretty gross, but it seems to have the same goal as `intercept` from `Test2::API`.

**Comment by exodist** [comment]
Please check the Test::Tester docs, I am pretty sure it documents not supporting subtests since forever.

If Test::Tester used to support subtests than I will fix it as a bug. If it never supported subtests then i will not bother. The idea was that Test::Tester should be replaced by intercept().

**Comment by Abigail** [comment]
If it's documented, I can't find it. Grepping for "sub *test" doesn't give any hits. 

The CAVEATS section mentions minimal support for testing note(), but is silent about subtest.

**Comment by exodist** [comment]
I just tried this using the last Test-Simple released before Test2 was introduced.

```
$ perl -e 'use Test::Tester; use Test::More; print "$Test::More::VERSION\n"; run_tests sub {subtest Foo => sub {pass}};'
1.001014
Use of uninitialized value in concatenation (.) or string at /home/exodist/.perlbrew/libs/5.20.0_thr@foo/lib/perl5/Test/Builder.pm line 200.
Can't use an undefined value as a symbol reference at /home/exodist/.perlbrew/libs/5.20.0_thr@foo/lib/perl5/Test/Builder.pm line 1826.
Use of uninitialized value in numeric eq (==) at /home/exodist/.perlbrew/libs/5.20.0_thr@foo/lib/perl5/Test/Builder.pm line 410.
```

Which tells me this was never supported. And now that Test 2 introduced a much better system for testing test tools I have no intention of adding the new support to Test::Tester. That said, I would be willing to merge a PR if someone else wanted to do that work.

I was looking for the documentation on how to use the new system to test your tools, and it seems that documentation got deleted at some point! I will work on recreating it. (I will make a new issue for that)
