### ISSUE TITLE
Modification of a read-only value

### ISSUE THREAD

**Issue by jira** [Test-More/test-more#789]
There seems to be some weird interaction with Test::Script.
I'm using Test::Class and whenever I use script_compiles from Test::Script I get:
Modification of a read-only value attempted at /opt/perl/lib/site_perl/5.26.1/Test/Builder.pm line 1442.

Example code:
```
package Test;

use strict;
use warnings;

use base 'Test::Class';

use Test::More;
use Test::Script;

sub a_compilation_test : Test(startup => 1) {
  script_compiles('./t.pl');
}

sub test : Test(1) {
        ok(1);
}

package main;

use Test::Class;

Test::Class->runtests;
```
The content of the script passed to script_compiles makes no difference. It can be even empty.

**Comment by exodist** [comment]
What version of Test-Simple do you have installed?

**Comment by jira** [comment]
Should be the latest - 1.302096
