### ISSUE TITLE
Test-Simple-1.302096.tar.gz Issue

### ISSUE THREAD

**Issue by JesSelien123** [Test-More/test-more#793]
The cpan download has empty folders and has all the files at the root level.

perl Makefile.PL, will error:
WARNING: MIN_PERL_VERSION is not a known parameter.
'MIN_PERL_VERSION' is not a known MakeMaker parameter name.
Writing Makefile for Test::Simple

nmake test, error:
        C:\Perl\bin\perl.exe "-MExtUtils::Command::MM" "-e" "test_harness(0, 'bl
ib\lib', 'blib\arch')" t/*.t t/Legacy/*.t t/Legacy/Bugs/*.t t/Legacy/Builder/*.t
 t/Legacy/Regression/*.t t/Legacy/Simple/*.t t/Legacy/Test2/*.t t/Legacy/Tester/
*.t t/Legacy/subtest/*.t t/Legacy_And_Test2/*.t t/Test2/acceptance/*.t t/Test2/b
ehavior/*.t t/Test2/legacy/*.t t/Test2/modules/*.t t/Test2/modules/API/*.t t/Tes
t2/modules/Event/*.t t/Test2/modules/Event/TAP/*.t t/Test2/modules/EventFacet/*.
t t/Test2/modules/Formatter/*.t t/Test2/modules/Hub/*.t t/Test2/modules/Hub/Inte
rceptor/*.t t/Test2/modules/IPC/*.t t/Test2/modules/IPC/Driver/*.t t/Test2/modul
es/Tools/*.t t/Test2/modules/Util/*.t t/Test2/regression/*.t t/regression/*.t
FAILED--no tests were run for some reason.
NMAKE : fatal error U1077: 'C:\Perl\bin\perl.exe' : return code '0xff'
Stop.

I had to download from github for a working install.

**Comment by autarch** [comment]
This downloaded fine for me just now. Also, there's a new release out just recently.

**Comment by Leont** [comment]
>  WARNING: MIN_PERL_VERSION is not a known parameter.

That argument is unconditionally included, even though it's only supported on ExtUtils::MakeMaker 6.48 and above (which suggests you're running perl 5.8).  The warning is harmless but it would be nice if we could avoid it.

I wouldn't be surprised if any other issue you're observing is also specific to 5.8
