### ISSUE TITLE
Incorrect output from cmp_ok

### ISSUE THREAD

**Issue by tophopstop** [Test-More/test-more#795]
I've got an odd output from cmp_ok that I can't explain:
```perl
use Test::More;
use strict;
use warnings;
my $subTotal = 0;
cmp_ok $subTotal, '==', 0, q|is zero|;
$subTotal += 4.99;
cmp_ok $subTotal, '==', 4.99, q|add first|;
$subTotal += 19.99;
cmp_ok $subTotal, '==', 24.98, q|add second|;
done_testing;
```

Test fails with:
```
#   Failed test 'add second charge'
#   at simple.pl line 10.
#          got: 24.98
#     expected: 24.98
# Looks like you failed 1 test of 3.
```
Even more strange is that it appears to be data dependent.  If change the second number being added (and the expected result), it works:
```
use Test::More;
use strict;
use warnings;
my $subTotal = 0;
cmp_ok( $subTotal, '==', 0, q|is zero| );
$subTotal += 4.99;
cmp_ok( $subTotal, '==', 4.99, q|add first| );
$subTotal += 9.99;
cmp_ok( $subTotal, '==', 14.98, q|add second| );
done_testing;
```
Perl version: 5.14.4
Test::More version: 1.302098 (but also manifests on older versions, too.)

**Comment by exodist** [comment]
A coworker of mine saw similar issues in Test2::Tools::Compare recently, turns out it is a floating point issue:

```perl -e 'use Test2::V0; like("60.480000000000", number(60.48), "decimal"); like("60.480000000000", number(125 - 64.52), "subtraction"); done_testing'```

Diagnostics output shows the numbers being the same, but they ar enot because of IEEE floating point rules or something.

**Comment by exodist** [comment]
```
perl -e 'my $n1 = "60.48"; my $n2 = 125 - 64.52; print "$n1 | $n2\n"; print ($n1 == $n2 ? "same\n" : "not same\n")'
60.48 | 60.48
not same
```

This is not a Bug in Test::More or Test2. It is the way perl treats the numbers/values.

In Test2 I intend to make the diagnostics better. I am not sure of a good way to make them better in cmp_ok since it is more tied to the operators as perl uses them.

**Comment by tophopstop** [comment]
Ok, makes sense.  Thanks for the fast feedback!
