### ISSUE TITLE
Perl #109204: UTF-8 bug in Test::More and/or Test::Builder

### ISSUE THREAD

**Issue by xsawyerx** [Test-More/test-more#802]
Hi,

The following ticket was issued for Test::More in the Perl RT queue as [Perl #109204](https://rt.perl.org/Ticket/Display.html?id=109204). I would like to close it and instead open a corresponding one here.

The original ticket as follows:

On Fri, 27 Jan 2012 06:16:03 -0800, tom christiansen wrote:

As far as I can tell, it is not possible to reliably use Test::More's diag() function to reliably emit anything but pure ASCII.  This is not a documented restriction, and even if it were, it is still unacceptable.

The problem is that Test::Builder::_new_fh() doesn't set to the encoding on the output handle.  This causes a "Wide character in print".  Attempting to work around that by setting PERL_UNICODE (or running under -C) just moves the problem around.  It doesn't fix it.

Here are the four possibilities:

```
                                        -C0     -CS
                                        ----    ----
    run directly                        fail    pass
    run w/Test::Harness runtests        fail    fail
```

The only way to make it work is to run *without* a test harness and with -CS set, or for the test program to itself binmode STDOUT to utf8.

However, none of that works when run under a test harness.  That means there's no way to make it behave properly from a test harness.

Here's the simple demo test program:

```
    use utf8;
    use strict;
    use warnings;
    use charnames qw(:full);

    use Test::More;
    use Carp qw(cluck);

    ## Uncomment this to learn where the real problem is happening:
    ##
    ## $SIG{__WARN__} = sub { cluck "TRAPPED WARNING: @_" };

    my $sisyphus = "© 2011, Σίσυφος";

    diag("…starting Sisyphean tests");

    like   $sisyphus, qr/\N{COPYRIGHT SIGN}/, "it’s got a copyright sign";
    like   $sisyphus, qr/\p{sc=Greek}/, "græcum est: non potest legi";

    diag("¿Qué pasó?");

    done_testing();
```

This one screws up, and also produces illegal UTF-8:

```
    $ perl -C0 /tmp/badenc.t
    Wide character in print at /usr/local/lib/perl5/5.14.0/Test/Builder.pm
    line 1759.
    # …starting Sisyphean tests
    Wide character in print at /usr/local/lib/perl5/5.14.0/Test/Builder.pm
    line 1759.
    ok 1 - it’s got a copyright sign
    ok 2 - gr?cum est: non potest legi
    # ?Qu? pas??
    1..2
```

This is the only one that works:

```
    $ perl -CS /tmp/badenc.t
    # …starting Sisyphean tests
    ok 1 - it’s got a copyright sign
    ok 2 - græcum est: non potest legi
    # ¿Qué pasó?
    1..2
```

This one also screws up:

```
    $ perl -C0 -MTest::Harness -e 'runtests(@ARGV)' /tmp/badenc.t
    /tmp/badenc.t .. Wide character in print at
    /usr/local/lib/perl5/5.14.0/Test/Builder.pm line 1759.
    # …starting Sisyphean tests
    /tmp/badenc.t .. 1/? Wide character in print at
    /usr/local/lib/perl5/5.14.0/Test/Builder.pm line 1759.
    # ?Qu? pas??
       /tmp/badenc.t .. ok
    All tests successful.
    Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.05 cusr
    0.01 csys =  0.09 CPU)
    Result: PASS
```

And this doesn't help it at all -- notice the double encoding:

```
    $ perl -CS -MTest::Harness -e 'runtests(@ARGV)' /tmp/badenc.t
    /tmp/badenc.t .. Wide character in print at
    /usr/local/lib/perl5/5.14.0/Test/Builder.pm line 1759.
    # â<80>¦starting Sisyphean tests
    /tmp/badenc.t .. 1/? Wide character in print at
    /usr/local/lib/perl5/5.14.0/Test/Builder.pm line 1759.
    # ¿Qué pasó?
       /tmp/badenc.t .. ok
    All tests successful.
    Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.05 cusr
    0.01 csys =  0.09 CPU)
    Result: PASS
```

--tom

**Comment by Leont** [comment]
It is possible to do this in Test::Builder,it is even [documented](https://metacpan.org/pod/release/EXODIST/Test-Simple-1.001011/lib/Test/More.pm) (though the [idiomatic way](https://metacpan.org/pod/Test2::Plugin::UTF8) to do this in Test2 is different)

**Comment by xsawyerx** [comment]
Then it can be closed.

**Comment by exodist** [comment]
@xsawyerx can you please pass along leont's reply to tom?

Would it make sense to have Test2/Test::Builder detect the -Cx/PERL_UNICODE settings and handle them, or would that be problematic/asking for trouble?

**Comment by Grinnz** [comment]
I think that @Leont meant to link to https://metacpan.org/pod/Test::More#CAVEATS-and-NOTES
