### ISSUE TITLE
Can't locate object method "e" via package "warnings" ... on Strawberry Perl 5.14.4

### ISSUE THREAD

**Issue by twata1** [Test-More/test-more#821]
Hi,

Sometimes  I saw the results as follows.

http://www.cpantesters.org/cpan/report/57b02570-8db2-1014-8c15-62fce1e92b2e

Here is a sample script.
[simple_test.txt](https://github.com/Test-More/test-more/files/2676549/simple_test.txt)

[Execution result]
```
C:\home\heaven>prove -l simple_test.t
simple_test.t .. Can't locate object method "e" via package "warnings" at C:\home\heaven\perl5\lib\perl5/Test/More.pm line 3.
Compilation failed in require at simple_test.t line 6.
BEGIN failed--compilation aborted at simple_test.t line 6.
simple_test.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

Test Summary Report
-------------------
simple_test.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  2 wallclock secs ( 0.09 usr +  0.02 sys =  0.11 CPU)
Result: FAIL

C:\home\heaven>perl -MTest::Simple -e "print $Test::Simple::VERSION;"
1.302143
C:\home\heaven>
```

[Environment]
Windows 7(32bit)
Strawberry Perl 5.14.4

Thank you,

**Comment by exodist** [comment]
https://metacpan.org/source/EXODIST/Test-Simple-1.302143-TRIAL/lib/Test/More.pm

Considering the first 3 lines of Test::More at that version are:
```
package Test::More;
 
use 5.006;
use strict;
use warnings;
```

I can say there is a much deeper problem with the perl install, or other modules being used here. This is not a bug that can or should be solved in Test::More. This kind of thing could happen if Sub::UpLevel or the $CARP::Level are used improperly in a test (IE an error is tracing to the wrong file/line)
