### ISSUE TITLE
test suite leaks shm objects

### ISSUE THREAD

**Issue by tonycoz** [Test-More/test-more#823]
This came up first for the Test::Simple 1.302160 tests in core perl, but I reproduced it outside of core too.

To try and diagnose this I added code to perl's t/harness to report any extra ipc objects (using ipcs), and several Test-Simple test files had extra shm objects created:

Leaks found:
    ../cpan/Test-Simple/t/Test2/acceptance/try_it_fork.t:
         leaked shm id 17957026
    ../cpan/Test-Simple/t/Test2/acceptance/try_it_threads.t:
         leaked shm id 17989795
    ../cpan/Test-Simple/t/Test2/behavior/err_var.t:
         leaked shm id 18022564
    ../cpan/Test-Simple/t/Test2/behavior/ipc_wait_timeout.t:
         leaked shm id 18055333
    ../cpan/Test-Simple/t/Test2/modules/API.t:
         leaked shm id 18088102
    ../cpan/Test-Simple/t/Test2/modules/API/Breakage.t:
         leaked shm id 18120871
    ../cpan/Test-Simple/t/Test2/modules/API/Instance.t:
         leaked shm id 18153640
         leaked shm id 18186409
         leaked shm id 18219178
         leaked shm id 18251947
         leaked shm id 18284716
         leaked shm id 18317485
    ../cpan/Test-Simple/t/Test2/modules/API/Stack.t:
         leaked shm id 18350254
    ../cpan/Test-Simple/t/Test2/modules/Hub.t:
         leaked shm id 18383023
    ../cpan/Test-Simple/t/Test2/modules/IPC.t:
         leaked shm id 18415792
    ../cpan/Test-Simple/t/Test2/modules/IPC/Driver.t:
         leaked shm id 18448561
    ../cpan/Test-Simple/t/Test2/modules/Tools/Tiny.t:
         leaked shm id 18481330
    ../cpan/Test-Simple/t/Test2/regression/693_ipc_ordering.t:
         leaked shm id 18514099
    ../cpan/Test-Simple/t/Test2/regression/746-forking-subtest.t:
         leaked shm id 18546868
    ../cpan/Test-Simple/t/regression/fork_first.t:
         leaked shm id 17924257

This was consistent over more than one run.

I also tried testing with my system perl (5.24.1, Debian stable), using the cpan tool, taking a snapshot with ipcs before and after running the tests:

--- before.txt  2019-01-28 10:38:14.541049475 +1100
+++ after.txt   2019-01-28 10:39:40.109568485 +1100
@@ -198,6 +198,32 @@
 0x00000000 18907327   tony       666        64         0                       
 0x00000000 18940096   tony       666        64         0                       
 0x00000000 18972865   tony       666        64         0                       
+0x00000000 19005634   tony       666        64         0                       
+0x00000000 19038403   tony       666        64         0                       
+0x00000000 19071172   tony       666        64         0                       
+0x00000000 19103941   tony       666        64         0                       
+0x00000000 19136710   tony       666        64         0                       
+0x00000000 19169479   tony       666        64         0                       
+0x00000000 19202248   tony       666        64         0                       
+0x00000000 19235017   tony       666        64         0                       
+0x00000000 19267786   tony       666        64         0                       
+0x00000000 19300555   tony       666        64         0                       
+0x00000000 19333324   tony       666        64         0                       
+0x00000000 19366093   tony       666        64         0                       
+0x00000000 19398862   tony       666        64         0                       
+0x00000000 19431631   tony       666        64         0                       
+0x00000000 19464400   tony       666        64         0                       
+0x00000000 19497169   tony       666        64         0                       
+0x00000000 19529938   tony       666        64         0                       
+0x00000000 19562707   tony       666        64         0                       
+0x00000000 19595476   tony       666        64         0                       
+0x00000000 19628245   tony       666        64         0                       
+0x00000000 19661014   tony       666        64         0                       
+0x00000000 19693783   tony       666        64         0                       
+0x00000000 19726552   tony       666        64         0                       
+0x00000000 19759321   tony       666        64         0                       
+0x00000000 19792090   tony       666        64         0                       
+0x00000000 19824859   tony       666        64         0                       

After several minutes I took another snapshot and compared again and found no extra leaked shm objects.

I used the same code to check on darwin and received similar results:

Leaks found:
    ../cpan/Test-Simple/t/Test2/acceptance/try_it_fork.t:
         leaked shm id 65539
    ../cpan/Test-Simple/t/Test2/acceptance/try_it_threads.t:
         leaked shm id 65540
    ../cpan/Test-Simple/t/Test2/behavior/err_var.t:
         leaked shm id 65541
    ../cpan/Test-Simple/t/Test2/behavior/ipc_wait_timeout.t:
         leaked shm id 65542
    ../cpan/Test-Simple/t/Test2/modules/API.t:
         leaked shm id 65543
    ../cpan/Test-Simple/t/Test2/modules/API/Breakage.t:
         leaked shm id 65544
    ../cpan/Test-Simple/t/Test2/modules/API/Instance.t:
         leaked shm id 65545
         leaked shm id 65546
         leaked shm id 65547
         leaked shm id 65548
         leaked shm id 65549
         leaked shm id 65550
    ../cpan/Test-Simple/t/Test2/modules/API/Stack.t:
         leaked shm id 65551
    ../cpan/Test-Simple/t/Test2/modules/Hub.t:
         leaked shm id 65552
    ../cpan/Test-Simple/t/Test2/modules/IPC.t:
         leaked shm id 65553
    ../cpan/Test-Simple/t/Test2/modules/IPC/Driver.t:
         leaked shm id 65554
    ../cpan/Test-Simple/t/Test2/modules/Tools/Tiny.t:
         leaked shm id 65555
    ../cpan/Test-Simple/t/Test2/regression/693_ipc_ordering.t:
         leaked shm id 65556
    ../cpan/Test-Simple/t/Test2/regression/746-forking-subtest.t:
         leaked shm id 65557
    ../cpan/Test-Simple/t/regression/fork_first.t:
         leaked shm id 458754

To ensure it wasn't the leak check code being bad, I deleted all shm objects and did a normal make test_harness:

pallas:perl tony$ ipcs
IPC status from <running system> as of Mon Jan 28 11:37:21 AEDT 2019
T     ID     KEY        MODE       OWNER    GROUP
Message Queues:

T     ID     KEY        MODE       OWNER    GROUP
Shared Memory:
m 1310720 0x00000000 --rw-rw-rw-     tony    staff
m 131073 0x00000000 --rw-rw-rw-     tony    staff
m 524290 0x00000000 --rw-rw-rw-     tony    staff
m 131075 0x00000000 --rw-rw-rw-     tony    staff
m 131076 0x00000000 --rw-rw-rw-     tony    staff
m 131077 0x00000000 --rw-rw-rw-     tony    staff
m 131078 0x00000000 --rw-rw-rw-     tony    staff
m 131079 0x00000000 --rw-rw-rw-     tony    staff
m 131080 0x00000000 --rw-rw-rw-     tony    staff
m 131081 0x00000000 --rw-rw-rw-     tony    staff
m 131082 0x00000000 --rw-rw-rw-     tony    staff
m 131083 0x00000000 --rw-rw-rw-     tony    staff
m 131084 0x00000000 --rw-rw-rw-     tony    staff
m 131085 0x00000000 --rw-rw-rw-     tony    staff
m 131086 0x00000000 --rw-rw-rw-     tony    staff
m 131087 0x00000000 --rw-rw-rw-     tony    staff
m 131088 0x00000000 --rw-rw-rw-     tony    staff
m 131089 0x00000000 --rw-rw-rw-     tony    staff
m 131090 0x00000000 --rw-rw-rw-     tony    staff
m 393237 0x00000000 --rw-rw-rw-     tony    staff

T     ID     KEY        MODE       OWNER    GROUP
Semaphores:

**Comment by Leont** [comment]
In light of #815, I can't say I'm truly surprised.

**Comment by exodist** [comment]
I can verify, and am working on it. Expect a fix ASAP.
