### ISSUE TITLE
Test::Tester::Capture requires threads:shared

### ISSUE THREAD

**Issue by myrrhlin** [Test-More/test-more#826]
I was unable to install Test::Simple on redhat 7 because system perl is compiled with `USE_ITHREADS`, and Test::Tester::Capture then requires `threads::shared`, which I have not installed.  I dont really want to use threads -- but my only options right now appear to be get those modules, or roll my own perl.

Perhaps I am wrong, but:
The require could be wrapped in an eval, and Test:Simple could behave as if there are no threads, if the require fails.

**Comment by Leont** [comment]
`threads::shared` is part of the perl standard library, but by default Red Hat only installs part of the perl standard library. You need to install the `perl-core` package to get a fully-functional perl

**Comment by myrrhlin** [comment]
Understood: currently, if I'm using the redhat system perl, and want to use Test::Simple, then I must install threads and they will be used by tests.  If I don't like it, I can roll a different perl.

I was proposing a better/easier experience for this circumstance (a not implausible one for newer perl users), namely that the module in question could function without the threads library as if they were not enabled.  I'm not in a position to judge the merits vs costs of such a change, however.

Thanks for your attention!

**Comment by exodist** [comment]
Couple things:
1) Leont is correct, so technically nothing needs to be done here
2) I agree myrrhlin that it would not be hard to work around this, and I would probably accept a pr if you wrote one.
3) I am not sure threads::shared is even needed in this module anymore. I believe it was using it to emulate what Test::Builder **used** to do for threading support, however Test::Builder on Test2 no longer uses threads::shared under the hood. However extensive downstream/cpan testing would be needed to verify that nothing breaks if it is removed.
