### ISSUE TITLE
Subtest failures in forked process don't get handled the same way as tests

### ISSUE THREAD

**Issue by toddr** [Test-More/test-more#831]
If I fail in a child process while in a subtest, it is not detected.
```perl
use Test::More tests => 1;

subtest "subtest" => sub {
    plan tests => 1;
    pass("def");
    my $pid = fork;
    if($pid) {
        waitpid $pid, 0;
    }
    else {
        ok(0, "fail in child");
        exit;
    }
};
```

The output looks like this:
```
$>prove -wlvm t/bar.t
t/bar.t .. 
1..1
# Subtest: subtest
    1..1
    ok 1 - def
    not ok 2 - fail in child
    #   Failed test 'fail in child'
    #   at t/bar.t line 21.
ok 1 - subtest
ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.07 cusr  0.02 csys =  0.13 CPU)
Result: PASS
```

However if we take subtest out of the picture, it fails as one would hope it would. Shouldn't these be consistent?

```perl
use Test::More tests => 1;

pass("def");
my $pid = fork;
if($pid) {
    waitpid $pid, 0;
}
else {
    ok(0, "fail in child");
    exit;
}
```

The output without subtests:
```
$>prove -wlvm t/bar.t
t/bar.t .. 
1..1
ok 1 - def
not ok 2 - fail in child
#   Failed test 'fail in child'
#   at t/bar.t line 18.
All 1 subtests passed 

Test Summary Report
-------------------
t/bar.t (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  2
  Parse errors: Bad plan.  You planned 1 tests but ran 2.
Files=1, Tests=2,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.06 cusr  0.02 csys =  0.12 CPU)
Result: FAIL
```

**Comment by toddr** [comment]
This might be an issue with prove/yath, not Test::More

**Comment by exodist** [comment]
It does not look like you ever loaded any IPC support. Test::More before Test2 did not support forking inside tests at all, ti was not a bug, but a limitation. Before Test2 you had to use Test::SharedFork to make fork work, and doing so would break threading (so you had to pick one).

Test2 fixed this, and with Test2 you can use forking and threading, but first you must turn IPC support on (it is off by default as it causes a noticeable performance hit). If you load `use Test2::IPC` just after loading Test::More things work as expected
