### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by pali** [Test-More/test-more#834]
Currently Travis CI is turned off for this repository. But definition already exists: https://github.com/Test-More/test-more/blob/master/.travis.yml

Continuous integration can catch errors in pull requests and prevents merging code which is incompatible with tested perl versions.

**Comment by haarg** [comment]
Travis CI is enabled for this repo on [travis-ci.org](https://travis-ci.org/Test-More/test-more)

**Comment by pali** [comment]
Seems it is not enabled, or is enabled improperly... See commit page that there is no Travis report:
https://github.com/Test-More/test-more/commits/master

Also last two merged pull requests https://github.com/Test-More/test-more/pull/825 and https://github.com/Test-More/test-more/pull/824 do not have any report from Travis...

**Comment by exodist** [comment]
@pali is right. I have been wondering why Travis only runs for master and not PR's, but have not had time to look into it. I would like this issue fixed eventually either when I have time, or when someone who knows more about travis can fix it.

**Comment by pali** [comment]
I saw this phenomena in past... I tried to revoke Travis access in github settings and disabled and enabled repository on Travis... and it somehow helped. But so not know what was reason or what fixed. If you have time you can try it...

**Comment by pali** [comment]
Really, just disabling it and enabling it again should help.

**Comment by exodist** [comment]
You make it sound so simple, but it was hard to find. First I had to re-sync the account, then I had to grant access to the test-more organization, then I had to re-sync things, then I had to select the org, then I had to manually find it in a multi-page list because the filter tool is apparently broken and hid the project when I typed in the name.

That said I did eventually find it, and I turned it off, then back on again.

**Comment by pali** [comment]
Ou, seems that every one year it is more and more complicated.

But important is that now you have fixed it! I opened pull request https://github.com/Test-More/test-more/pull/845 and travis was triggered to run tests for open pull request.

So thank you for fixing it, seems that turn off and on again helped!
