### ISSUE TITLE
No introspection when complaining about other installation parties

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#836]
Today I saw this message and it poses questions (I think it is irrelevant in which package it happened):

``` text
t/02_pp_impl.t ......... 13/? # Looks like you failed 1 test of 13.

You have loaded versions of test modules known to have problems with Test2.
This could explain some test failures.
 * Module 'Test::Exception' is outdated, we recommed updating above 0.42.

t/02_pp_impl.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 
```

- who wrote this text (Module, version, probably code line); since the text mentiones Test2 I suppose I can report it here, if this is not the right place, can you suggest a bette one?
- what does this code that wrote the above believe is the version that is outdated

Please note that the perl that produced this output has :

```
Test::Exception is up to date (0.43).
```

What gives?

What a luck that there is this typo. Greeping for 'recommed updating above' finde Test-Simple-1.302164/lib/Test2/API/Breakage.pm

Let me know when you need further information.

Regards,.

**Comment by exodist** [comment]
The code in question does a simple Test::Exception->VERSION('0.42') check, if it throws an exception it reports it as out of date. So what we need to do is figure out why your installation of Test::Exception is failing that version check and then work around it somehow.

In Test2::API::Breakage on line 76 I recommend adding $@ to the error message (locally on your machine) and then re-running this test to see what exception the version check throws. With that information I may be better able to fix this.

**Comment by andk** [comment]
$@ was not helpful enough, so I added the INC and it showed that the tested module had an outdated Test::Exception in its inc/ directory, shadowing the newer installed Test::Exception. So this is my change for debugging:

``` diff
--- lib/Test2/API/Breakage.pm   2017-11-18 17:54:35.000000000 +0000
+++ /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.27.5-435-gfeee2c5b74/1e0c/lib/5.27.6/Test2/API/Breakage.pm    2019-07-15 04:09:48.696180012 +0000
@@ -73,7 +73,9 @@
         next unless $INC{$file} || ($require && eval { require $file; 1 });
         my $want = $suggest{$mod};
         next if eval { $mod->VERSION($want); 1 };
-        push @warn => " * Module '$mod' is outdated, we recommed updating above $want.";
+        my $error = $@;
+        chomp $error;
+        push @warn => " * Module '$mod' is outdated, we recommed updating above $want. error was: '$error'; INC is $INC{$file}";
     }
     
     for my $mod (keys %required) {
```

and this is the output that it produced:
``` text
You have loaded versions of test modules known to have problems with Test2.
This could explain some test failures.
 * Module 'Test::Exception' is outdated, we recommed updating above 0.42. error was: 'Test::Exception version 0.42 required--this is only version 0.29 at /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.27.5-435-gfeee2c5b74/1e0c/lib/5.27.6/Test2/API/Breakage.pm line 75.'; INC is /tmp/loop_over_bdir-bQg7EB/Algorithm-KernelKMeans-0.03-0/inc/Test/Exception.pm
```

Software can be so surprising.
