### ISSUE TITLE
many warnings during global destruction

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#837]
in a complicated test where some objects are created with subrefs that call Test::More::ok, I see this at the end (during global destruction):

```
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 343 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 437 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 438 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API/Context.pm line 129 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API/Context.pm line 129 during global destruction.
Use of uninitialized value $hid in delete at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API/Context.pm line 133 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 343 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 437 during global destruction.
Use of uninitialized value $hid in hash element at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API.pm line 438 during global destruction.
        (in cleanup)    (in cleanup)  at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test/Builder.pm line 415 during global destruction.
        (in cleanup)    (in cleanup)  at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/Test2/API/Context.pm line 73 during global destruction.
```

It would appear that some objects are being created, and then torn down in the wrong order so some undef values are appearing in places where normal runtime code would not expect them.

The general solution to this is to add explicit DESTROY methods to all classes that require them, to control the order in which objects are destroyed.  I could explicitly `undef $foo` myself in my test file for various objects, but they are all internal objects constructed by Test2::API and I'm unable to tell what they are, precisely.

**Comment by exodist** [comment]
Can you verify you are using the latest version? Assuming you are, can you give me a minimal reproduction case?

Thanks for the report!

**Comment by karenetheridge** [comment]
Yes, Test-Simple is current.

A small repro case is difficult; a large number of things need to be loaded in order for objects to be destroyed in the "wrong" order.

**Comment by haarg** [comment]
I've run into this issue testing older versions of Moo.  I don't have a "sensible" test, but here a reduced example that will show trigger the warnings.
```
use strict;
use warnings;
use Test::More tests => 1;
Test::More->builder->no_ending(1);

package Bar;

sub DESTROY { ::ok 1 }

our $bar = bless {}, 'Bar';
```
The issue started after f83b4ef377f4cc1b3ab39c1dde001a92c7cb1824, which causes Term::Table to be loaded.  This then loads Unicode::GCString and uses Unicode properties in a regex.  That combined seems to be enough to perturb the global destruction order enough to cause issues.

**Comment by haarg** [comment]
I've created a PR that delays loading Term::Table until it is actually needed.  This fixes this issue for my case, and seems like generally a good idea.  I don't know if it covers all cases though.
