### ISSUE TITLE
t/Test2/modules/API.t: Throws "used only once" earning in two locations

### ISSUE THREAD

**Issue by jkeenan** [Test-More/test-more#839]
I observed the following warnings coming from the Test-Simple test suite in the course of synching Perl 5 blead to Test-Simple version 1.302168.
```
t/Test2/legacy/TAP.t ........................... ok
Name "main::cleanup2" used only once: possible typo at t/Test2/modules/API.t line 310.
Name "main::cleanup1" used only once: possible typo at t/Test2/modules/API.t line 4.
t/Test2/modules/API.t .......................... ok
```
Please consider the patch attached.
[0001-Avoid-used-only-once-warnings-in-BEGIN-and-END-block.patch.txt](https://github.com/Test-More/test-more/files/3611119/0001-Avoid-used-only-once-warnings-in-BEGIN-and-END-block.patch.txt)

Thank you very much.
Jim Keenan

**Comment by exodist** [comment]
Patch applied, it will go out with my next release.

**Comment by jkeenan** [comment]
Confirmed, as part of testing during synchronization of Perl 5 blead (cd42a730c529f058bb29066bec486df8278d437b) with this version of Test-Simple distribution.

Thank you very much.
Jim Keenan
