### ISSUE TITLE
Small docs inaccuracy: Test2::Hub

### ISSUE THREAD

**Issue by FGasper** [Test-More/test-more#844]
The docs say for `plan()`:
> Get or set the plan. The plan must be an integer larger than 0, the string 'no_plan', or the string 'skip_all'.

… but when I try that I get:
```
'no_plan' is not a valid plan! Plan must be an integer greater than 0, 'NO PLAN', or 'SKIP' at /opt/local/lib/perl5/site_perl/5.26/Test2/Hub.pm line 509.
```

Looks like this doc just needs that small correction?

Thank you!

**Comment by exodist** [comment]
Thanks, I will look into it :-)
