### ISSUE TITLE
Travis is not running 5.6 tests under 5.6

### ISSUE THREAD

**Issue by exodist** [Test-More/test-more#847]
https://travis-ci.org/Test-More/test-more/jobs/638547746?utm_medium=notification&utm_source=github_status

Read the console output. Travis failes to find/install 5.6, and instead runs all the tests under a recent perl version.

@pali since you are so keen on 5.6 support and travis support I figured you may want to be aware of this.

**Comment by exodist** [comment]
Just looked, this is a problem on all the travis perl versions, they all fail to install the proper perl and instead use the already installed perl, which is not the right version.

**Comment by exodist** [comment]
See every build on https://travis-ci.org/Test-More/test-more/builds/638547745  they are all failing to install the desired perl version, but tests pass anyway.

**Comment by pali** [comment]
This is tricky. Travis hides important details. Please look at line `eval $(curl https://travis-perl.github.io/init) --auto` and expand it. After that you would see:

```
$ build-perl
Downloading pre-built Perl 5.6.2...
...
$ perl -V
Summary of my perl5 (revision 5.0 version 6 subversion 2) configuration:
  Platform:
    osname=linux, osvers=2.6.32-042stab090.5, archname=x86_64-linux
```

Problem is that Travis first say that it does not have Perl 5.6.2, then it prints `$ perl --version` output and after that it executes `eval $(curl https://travis-perl.github.io/init) --auto` which install Perl 5.6.2 version. And it hides all important details, so to see it you need to expand output.

So everything is working fine, just you need to look at whole output, not only at first lines. I know that this is really confusing, be we cannot do anything with it. Just properly read all output lines, included hidden.

**Comment by pali** [comment]
You can look also at test output, where is written:
```
# DIAGNOSTICS INFO IN CASE OF FAILURE:
# Perl: 5.006002
```
So it is just another proof that correct perl version was installed and is in use.

**Comment by exodist** [comment]
ah, I see it now, thanks
