### ISSUE TITLE
Value: Can't locate JSON/PP.pm in @INC

### ISSUE THREAD

**Issue by smuth4** [Test-More/test-more#851]
While installing the latest version on Perl 5.10.1, this error occurred:
```
# Failed test 'Leftover files'
# at t/Test2/modules/IPC/Driver/Files.t line 220.
# Value: Can't locate JSON/PP.pm in @INC (@INC contains: /root/.cpanm/work/1585570634.10082/Test-Simple-1.302173/blib/lib /root/.cpanm/work/1585570634.10082/Test-Simple-1.302173/blib/arch /usr/local/lib/perl5 /usr/local/share/perl5 /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5 /usr/share/perl5 .) at /root/.cpanm/work/1585570634.10082/Test-Simple-1.302173/blib/lib/Test2/IPC/Driver/Files.pm line 132.
# IPC Fatal Error: Leftover files in the directory (/tmp/test2~10668~2VupGp/12345~1~1~1~10668~0~1~Foo.ready)!
#   (in cleanup) 255 at t/Test2/modules/IPC/Driver/Files.t line 140.
# Does not match: (?-xism:IPC Fatal Error: Not all files from hub '12345~1~1~1' have been collected)
t/Test2/modules/IPC/Driver/Files.t .............
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/65 subtests
```

It looks like 0b4cd83648378c157a5e141bb7fc010cd6db9065 introduced JSON::PP as a implicit dependency, which only joined core in 5.14. `sudo cpanm JSON::PP && sudo cpanm EXODIST/Test-Simple-1.302173.tar.gz` succeeded as a workaround for this issue.

**Comment by exodist** [comment]
Thanks, I will fix this.

It is only supposed to load it if things have already failed
catastrophically, but I will still make it better and fail catastrophically
without json being mistakenly listed as the cause.

**Comment by exodist** [comment]
oh, I see now, a test was testing that catastrophic failure codepath, meaning the tests could not pass on 5.10 and below. I missed that on my first glance. Anyway, should be fixed in git, verifying it locally on old perl version, then I will release

**Comment by smuth4** [comment]
Great, thanks!
