### ISSUE TITLE
Without special workaround, t/Legacy/Tester/tbt_08subtest.t fails on Win32 in core distribution

### ISSUE THREAD

**Issue by jkeenan** [Test-More/test-more#853]
One of the major changes introduced in perl-5.28 in 2018 was a security fix which caused directory . to no longer be automatically included in `@INC`. Prior to that production release, we had to make certain workarounds in an important component of the Perl 5 testing infrastructure, `t/TEST`, to accommodate three CPAN distributions which are shipped with the Perl 5 core distribution.

Test-Simple was one of those distributions.  We would like to be able to remove the workaround from `t/TEST`.  Yesterday I created a branch in the core repository to do just that.  Everything tested fine on Linux, but not on Windows.  The core currently has "github Actions" set up to do test builds on MSWin32 machines (one with MSVC, one with MingW).  One test in the cpan/Test-Simple directory failed on Windows.

```
../cpan/Test-Simple/t/Legacy/Tester/tbt_08subtest.t ................ ok
do "t\Legacy\Tester\tbt_09do_script.pl" failed, '.' is no longer in @INC; did you mean do "./t\Legacy\Tester\tbt_09do_script.pl"? at t/Legacy/Tester/tbt_09do.t line 14.

#   Failed test 'do succeeded'
#   at t/Legacy/Tester/tbt_09do.t line 15.
#   $! is 'No such file or directory'
# Looks like you planned 3 tests but ran 1.
# Looks like you failed 1 test of 1 run.
../cpan/Test-Simple/t/Legacy/Tester/tbt_09do.t ..................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 3/3 subtests 
```
Here is an extract from the raw test report
```
2020-04-12T03:46:49.6496996Z do "t\Legacy\Tester\tbt_09do_script.pl" failed, '.' is no longer in @INC; did you mean do "./t\Legacy\Tester\tbt_09do_script.pl"? at t/Legacy/Tester/tbt_09do.t line 14.
2020-04-12T03:46:49.6497188Z ../cpan/Test-Simple/t/Legacy/undef.t ............................... ok
2020-04-12T03:46:49.6510817Z 
2020-04-12T03:46:49.6527282Z #   Failed test 'do succeeded'
2020-04-12T03:46:49.6545757Z #   at t/Legacy/Tester/tbt_09do.t line 15.
2020-04-12T03:46:49.6548360Z #   $! is 'No such file or directory'
2020-04-12T03:46:49.6608391Z # Looks like you planned 3 tests but ran 1.
2020-04-12T03:46:49.6608602Z ../cpan/Test-Simple/t/Legacy/Tester/tbt_09do.t ..................... 
2020-04-12T03:46:52.3332528Z # Looks like you failed 1 test of 1 run.
2020-04-12T03:46:52.3332789Z Dubious, test returned 1 (wstat 256, 0x100)
2020-04-12T03:46:52.3333008Z Failed 3/3 subtests 
```

I don't have Win32 available.  Can this test file be adapted such that when run through the core test suite's test harness (`make test` or `make test_harness`), it does not encounter this problem on Windows?

Thank you very much.
Jim Keenan

**Comment by exodist** [comment]
Hmm, the test predates me. I am guessing we can probably just change the line to start with `./`... I would be surprised if there were any tests to verify '.' in @INC behavior, rather I suspect they all just assumed it, probably unknowingly.

I will look into it.

**Comment by jkeenan** [comment]
On 4/12/20 12:58 PM, Chad Granum wrote:
> Hmm, the test predates me. I am guessing we can probably just change the 
> line to start with |./|... I would be surprised if there were any tests 
> to verify '.' in @inc <https://github.com/inc> behavior, rather I 
> suspect they all just assumed it, probably unknowingly.
> 
> I will look into it.
> 

I played around with it for an hour.  ISTR that 'do $file' was one of 
things that needed a lot of @INC fixing two years ago.  But, lacking 
Win32, I couldn't get it straight.

Send me any patch that works for you and I'll try it in this branch in core.

Thanks.
jimk
