### ISSUE TITLE
smartmatch warnings with cmp_ok

### ISSUE THREAD

**Issue by eserte** [Test-More/test-more#870]
If using `~~` in `cmp_ok` then one gets a warnings which cannot be ceased. A sample test script:
```
#!/usr/bin/perl

use strict;
use warnings;
no if $] >= 5.018, warnings =>  "experimental::smartmatch";
use Test::More 'no_plan';

cmp_ok 1, "~~", 1;

__END__
```
Output is:
```
Smartmatch is experimental at (eval in cmp_ok) /tmp/t.pl line 8.
ok 1
1..1
```

A possible fix is to prepend something like this into the string eval used at `Test::Builder::cmp_ok`:
```
($type eq '~~' && !warnings::enabled_at_level("experimental::smartmatch", 1) ? qq[no warnings "experimental::smartmatch";\n] : '')
```
(I can create a PR if this issue & workaround is accepted)

**Comment by exodist** [comment]
I created https://github.com/Test-More/test-more/pull/871  which I think is a better solution to the issue, though I want to get feedback before merging it.
