### ISSUE TITLE
Bumping List::Util version caused a circular dependency

### ISSUE THREAD

**Issue by AvriBalofsky** [Test-More/test-more#873]
Any package that requires Test::More is now failing unless --notest is passed in at some point.

On a centos7 docker image...

> /]# cpanm Test::More
> --> Working on Test::More
> Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302180.tar.gz ... OK
> Configuring Test-Simple-1.302180 ... OK
> ==> Found dependencies: List::Util
> --> Working on List::Util
> Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.55.tar.gz ... OK
> Configuring Scalar-List-Utils-1.55 ... OK
> ==> Found dependencies: Test::More
> ! Installing the dependencies failed: Module 'Test::More' is not installed
> ! Bailing out the installation for Scalar-List-Utils-1.55.
> ! Installing the dependencies failed: Installed version (1.27) of List::Util is not in range '1.45'
> ! Bailing out the installation for Test-Simple-1.302180.

> /]# cpanm List::Util
> --> Working on List::Util
> Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.55.tar.gz ... OK
> Configuring Scalar-List-Utils-1.55 ... OK
> ==> Found dependencies: Test::More
> --> Working on Test::More
> Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302180.tar.gz ... OK
> Configuring Test-Simple-1.302180 ... OK
> ==> Found dependencies: List::Util
> ! Installing the dependencies failed: Installed version (1.27) of List::Util is not in range '1.45'
> ! Bailing out the installation for Test-Simple-1.302180.
> ! Installing the dependencies failed: Module 'Test::More' is not installed
> ! Bailing out the installation for Scalar-List-Utils-1.55.

**Comment by exodist** [comment]
I will release this once my downstream testing is complete, so ~1 hour. Sorry about this. I am extra annoyed at myself for not realizing I was no longer using `uniq` by the end of the patch and never actually needed the version bump.

**Comment by AvriBalofsky** [comment]
Thanks!
