### ISSUE TITLE
yath misses failure that prove catches

### ISSUE THREAD

**Issue by FGasper** [Test-More/test-more#878]
```
#!perl

use strict;
use warnings;

use Test::More;
use Test::FailWarnings;

use File::Temp;
my ($tfh, $tpath) = File::Temp::tempfile( CLEANUP => 1 );
print {$tfh} join(
    "\n",
    'package NoWarns;',
    'use strict;',
    'sub bogus { system q<does-not-exist> }',
    '1;',
    q<>
);
close $tfh;

require $tpath;

NoWarns::bogus();

ok 1;

done_testing;
```
^^ yath will pass that, but prove fails it.

**Comment by FGasper** [comment]
`yath --switch=-w` behaves the same as `prove -w`. Closing.

**Comment by exodist** [comment]
To clarify, the problem here is that prove was being run with `-w` but yath was not given equivelent instructions. Yath witht he -w switch and prove with -w both see the issues, prove and yath without -w both see no issue. So the behavior difference was because of incompatible usages, not a bug.
