### ISSUE TITLE
cmp_ok() can fail to handle overloading of '!='

### ISSUE THREAD

**Issue by sisyphus** [Test-More/test-more#896]
Following on from https://www.perlmonks.org/?node_id=11144043.
AFAIK, the issue arises only with the overloaded '!=' operator, and then only when the cmp_ok() test fails.
Here's the demo script:
```
# try.pl
use Test::More;
package Ov {
  use overload (
    '""' => sub { 'x' },
    '!=' => sub { 0 },
  );
};
cmp_ok(bless({}, 'Ov'), '!=', bless({}, 'Ov'), 'failing test');
done_testing();
```
Here's the output:
```
C:\pscrpt\>perl try.pl
not ok 1 - failing test
#   Failed test 'failing test'
#   at try.pl line 8.
Operation "eq": no method found,
        left argument in overloaded package Ov,
        right argument in overloaded package Ov at C:/perl-5.34.0/site/lib/Test/Builder.pm line 1006.
A context appears to have been destroyed without first calling release().
Based on $@ it does not look like an exception was thrown (this is not always
a reliable test)

This is a problem because the global error variables ($!, $@, and $?) will
not be restored. In addition some release callbacks will not work properly from
inside a DESTROY method.

Here are the context creation details, just in case a tool forgot to call
release():
  File: try.pl
  Line: 8
  Tool: Test::More::cmp_ok

Here is a trace to the code that caused the context to be destroyed, this could
be an exit(), a goto, or simply the end of a scope:
Context destroyed at C:/perl-5.34.0/site/lib/Test/Builder.pm line 1006.
        eval {...} called at C:/perl-5.34.0/site/lib/Test/Builder.pm line 1006
        Test::Builder::cmp_ok(Test::Builder=HASH(0x66dc60), Ov=HASH(0x64c5b8), "!=",
 Ov=HASH(0x33c938), "failing test") called at C:/perl-5.34.0/site/lib/Test/More.pm line 511
        Test::More::cmp_ok(Ov=HASH(0x64c5b8), "!=", Ov=HASH(0x33c938), "failing
test") called at try.pl line 8


Cleaning up the CONTEXT stack...
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
```
The most pertinent information therein is the reference to C:/perl-5.34.0/site/lib/Test/Builder.pm line 1006, which contains:
```
my $eq = ($got eq $expect || $got == $expect) 
```
thereby hinting at the reason that overloading of 'eq' is being deemed necessary.

This disaster is avoided if '0+' overloading is provided.
In the actual case where I first struck this issue, I was also able to work around the problem by providing 'eq' overloading, without having to overload '0+'.

Cheers,
Rob

**Comment by haarg** [comment]
The full statement triggering the issue is:
```perl
            my $eq = ($got eq $expect || $got == $expect)
                && (
                    (defined($got) xor defined($expect))
                 || (length($got)  !=  length($expect))
                );
```
This was added by 6717dcca107274fb8c46cab65d2eec49446693a1.

I don't really understand why the condition exists like this. This code is only run if the original comparison failed, and if the comparison is a `ne` or `!=`. So we already know that `$got` and `$expect` compared equal. And what is the purpose of the length check? It seems like it could be simplified to:
```perl
            my $eq = (defined($got) xor defined($expect));
```
Or, since that variable name is confusing, the entire `elsif` block could be simplified to:
```perl
        elsif( $type =~ /^(ne|!=)$/ ) {
            if (defined($got) xor defined($expect)) {
                $self->_cmp_diag( $got, $type, $expect );
            }
            else {
                $self->_isnt_diag( $got, $type );
            }
        }
```

**Comment by hvds** [comment]
> So we already know that `$got` and `$expect` compared equal.

Ah, but that was before the `->$unoverload` call maybe modified them.

Even then, I can't really tell what this whole chunk is trying to do. I think it needs to make its mind up though: either it wants to treat the value both as string and as number, in which case it should "unoverload" both stringify and numify; or it wants to treat it just as the type relevant to the comparator, in which case the `ne` and `!=` cases probably have to be handled separately. (I suspect the latter is the correct solution.)
