### ISSUE TITLE
Test::More::isn't() will emit warning as of perl-5.37.9

### ISSUE THREAD

**Issue by jkeenan** [Test-More/test-more#903]
As of a recent commit to the Perl 5 core distribution ...
```
commit 7e2d91e6d3a09e2ebb61242bb18ff95d30d9560d
Author: Tony Cook <tony@develop-help.com>
Date:   Wed Dec 7 16:17:45 2022 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Tue Feb 7 10:37:30 2023 +1100

    toke.c: deprecation warning for ' as a package separator
    
    First stage of RFC 0015.
    
    This also changes the warning for ' as package separator in
    quoted strings to also be a deprecation warning.
```
... `Test::More::isn't()` now generates a deprecation warning.
```
$ perl -v | head -2 | tail -1
This is perl 5, version 32, subversion 1 (v5.32.1) built for amd64-freebsd-thread-multi

$ bleadperl -v | head -2 | tail -1
This is perl 5, version 37, subversion 9 (v5.37.9 (v5.37.8-86-g35b3adc04e)) built for amd64-freebsd-thread-multi

$ bleadperl -MTest::More -E 'say $Test::More::VERSION;'
1.302192

$ cat isnt.pl
#!/usr/bin/env perl
use strict;
use warnings;
use Test::More qw( no_plan );

my ($x, $y) = qw( alpha beta );
isn't $x, $y, "One of these things is not like the other";

$ perl isnt.pl
ok 1 - One of these things is not like the other
1..1

$ bleadperl isnt.pl
Old package separator "'" deprecated at isnt.pl line 7.
ok 1 - One of these things is not like the other
1..1
```
Test::More documents the `isn't()` function like this:
```
For those grammatical pedants out there, there's an "isn't()"
function which is an alias of "isnt()".
```
Is it time to deprecate this function so that its users are not surprised by a warning generated by `perl` itself?

Apart from Test::More itself, there are at least two other distributions that are shipped with the core distribution whose tests use `isn't()`:  `parent` and `TermCap`.

**Comment by demerphq** [comment]
I think we can close this now? Or perhaps we should wait until the release is rolled? I am looking forward to using the new sync-with-cpan hacks I did this week. :-)

**Comment by demerphq** [comment]
See #905 there was a typo in the Changes file for this issue. :-)

**Comment by demerphq** [comment]
I have pushed a patch to synchronize core to the latest version. (We dont store a copy of the Changes, and I manually updated the text in the commit) https://github.com/Perl/perl5/pull/20907

**Comment by demerphq** [comment]
I think this can be closed now.
