### ISSUE TITLE
CPAN test failures on 5.10

### ISSUE THREAD

**Issue by djerius** [Test-More/test-more#909]
Howdy,

`Test-Simple-1.302193` is racking up failures on 5.10.x on [CPAN testers](https://www.cpantesters.org/distro/T/Test-Simple.html?oncpan=1&distmat=1&version=1.302193&grade=3).

The failures all seem to be in `t/Legacy/More.t`

```
t/Legacy/missing.t ............................... ok

#   Failed test '$@ untouched'
#   at t/Legacy/More.t line 200.
#          got: ''
#     expected: 'this should not be touched'

#   Failed test '$! untouched'
#   at t/Legacy/More.t line 201.
#          got: 
#     expected: 42
# Looks like you failed 2 tests of 57.
t/Legacy/More.t .................................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/57 subtests 
```

**Comment by haarg** [comment]
I can reproduce this with a fresh install of perl 5.10.1 with threads.

**Comment by exodist** [comment]
@haarg how did you install 5.10.1? If it was perlbrew can you give me your install command?

**Comment by exodist** [comment]
Thanks to Haarg we discovered I already fixed this and released a fix. I was looking at reports for the old version, and haarg wrote a patch for the old version. Upon trying to resolve a conflict in the PR we realized I already fixed this.
