### ISSUE TITLE
Whoa

### ISSUE THREAD

**Issue by philiprbrenan** [Test-More/test-more#916]
![whoa](https://github.com/Test-More/test-more/assets/7548378/f2dab5f8-0719-4a5f-9809-eb7efc52bdd5)

Contacting the author immediately as requested.

Test::More is very useful: I use it many  times every day.

**Comment by jkeenan** [comment]
Could you present the context in which your program is calling Data::Table::Text and thus encountering this problem?  (*i.e.,* a stripped-down code sample)

**Comment by jkeenan** [comment]
The image you've embedded suggests that this began in a call to Test::More::is_deeply(), but the place where that is called is cut-off at `cpan/Z`.

**Comment by philiprbrenan** [comment]
The problem occurs when **is_deeply** is  handed an address inside a **vec()** string, as in **\vec($a, 2, 32).**  I imagine it might be possible to achieve a similar effect with **substr**, **split** or any other function that can act as a left hand value.
