### ISSUE TITLE
Test2 broken in the presence of a `fork` under Windows

### ISSUE THREAD

**Issue by mkende** [Test-More/test-more#928]
# Overview

Forking on Windows inside a Perl program being tested using `Test2` fails with error:

> Test2 must be fully loaded before you start a new thread!

# Step to reproduce

This is a minimal example that allows to reproduce the issue:

```perl
use Test2::V0;

if (fork) {
  pass();
  done_testing;
}
```

# Expected output

When run on Linux, that program outputs the following:

```
# Seeded srand with seed '20240413' from local date.
ok 1
1..1
```

# Actual output

When run on Windows, that program outputs the following:

```
Test2 must be fully loaded before you start a new thread!
 at D:\Temp SSD\test.pl line 3.
```

# Workaround

Adding the following line after the `use` statement seems to fix the issue.

```perl
Test2::API::test2_load;
```

However, I’m not sure this is a great idea to do that on my side given that the call is not even documented.

**Comment by exodist** [comment]
To use forking or threads you need to load Test2::IPC


use Test2::IPC;

**Comment by mkende** [comment]
Thanks, I had missed that part. Sorry for the noise.
