### ISSUE TITLE
Aug4th update breaking log::log4perl install?

### ISSUE THREAD

**Issue by bobkanick** [Test-More/test-more#998]
My apologies if this issue post is in error, but it appears from my attempts to install Log::Log4perl that the most recent change to this Test-More module has broken it's install as a dependency for Log4perl.  I get the following from Docker when it attempts to load Log4perl...

#6 170.6 --> Working on Log::Log4perl
#6 170.6 Fetching http://www.cpan.org/authors/id/E/ET/ETJ/Log-Log4perl-1.57.tar.gz ... OK
#6 170.9 Configuring Log-Log4perl-1.57 ... OK
#6 171.1 ==> Found dependencies: Test::More
#6 171.1 --> Working on Test::More
#6 171.1 Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302200.tar.gz ... OK
#6 171.6 Configuring Test-Simple-1.302200 ... OK
#6 171.8 ==> Found dependencies: Term::Table
#6 171.9 --> Working on Term::Table
#6 171.9 Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Term-Table-0.018.tar.gz ... OK
#6 172.0 Configuring Term-Table-0.018 ... OK
#6 172.1 ==> Found dependencies: Test2::Tools::Tiny
#6 172.2 ! Installing the dependencies failed: Module 'Test2::Tools::Tiny' is not installed
#6 172.2 ! Bailing out the installation for Term-Table-0.018.
#6 172.2 ! Installing the dependencies failed: Module 'Term::Table' is not installed
#6 172.2 ! Bailing out the installation for Test-Simple-1.302200.
#6 172.2 ! Installing the dependencies failed: Module 'Test::More' is not installed
#6 172.2 ! Bailing out the installation for Log-Log4perl-1.57.

So I'm presuming that this failure has to do with Test-More because it is the only module that has changed recently.  Again, apologies if I am misreading this.

**Comment by exodist** [comment]
Look like I introduced a circular dep. Can you tell me what version if perl you encounteres this issue on?

**Comment by bobkanick** [comment]
I'm installing this in a Docker image on an Amazon base image, "al2", that is limited to PERL-5.16.3

**Comment by exodist** [comment]
I have released Term::Table 0.020  which fixes the issue. You will have to wait until Term::Table is on the mirrors/metacpan, so I would say give it at least an hour. Once the new Term:T:able (0.020) is installable the dep cycle should be broken and your install process should be fixed.

**Comment by bobkanick** [comment]
Thanks so much for the quick response!
